ignore:
  - "dace/jupyter.py"  # Omit files that cannot be tested
  - "dace/frontend/ml/tensorflow/**/*"  # Omit deprecated files
  - "samples/**/*"
  - "tests/**/*"

coverage:
  range: 40..90
  round: nearest
  status:
    patch:
      default:
        informational: true
    project:
      default:
        informational: true
#    project:
#      default:
#        threshold: 1%

codecov:
  notify:
    after_n_builds: 23

comment: false
