ignore:
  - "dace/jupyter.py"  # Omit files that cannot be tested
  - "dace/frontend/tensorflow/**/*"  # Omit deprecated files

coverage:
  range: 40..90
  round: nearest
  status:
    patch: off
    project:
      default:
        threshold: 1%

codecov:
    notify:
        after_n_builds: 8
