line-length = 120
target-version = "py310"

[lint]
select = ["F", "UP", "I"]
ignore = ["UP031","F821","F841","F823"]

[lint.per-file-ignores]
"__init__.py" = ["F401", "F403", "F405", "I"]

[format]
exclude = ["*.ipynb"]
