# Copyright 2019-2026 ETH Zurich and the DaCe authors. All rights reserved.
"""
Distribution of the thread-blocks of a GPU kernel over the chiplets (XCDs) of the target GPU.

Everything here is target-independent: whether a kernel is distributed, over how many chiplets, how
its grid is padded, and what the permutation and the trailing-block mask say. Both CUDA code
generators -- :mod:`dace.codegen.targets.cuda` and
:mod:`dace.codegen.targets.experimental_cuda` -- decide with these functions and differ only in
where they write the resulting text, so the two cannot drift apart.
"""

import warnings
from typing import List, Optional, Tuple

from dace import symbolic
from dace.codegen import common
from dace.config import Config
from dace.sdfg import nodes


def detected_chiplet_count(backend: str) -> int:
    """
    Returns the number of chiplets of the GPU of this machine, or 1 if it cannot be determined.

    Called when the ``compiler.cuda.chiplet_number`` configuration entry is left at its default of 0,
    which means that the number of chiplets has not been configured by the user. A detected number is
    written back to that entry, so that the rest of the process sees the number the code is generated
    for. Only the HIP backend is queried, chiplets being a feature of AMD GPUs, and a failure to
    determine the number leaves the entry alone and disables the distribution.

    :param backend: GPU backend the code is generated for, ``'cuda'`` or ``'hip'``.
    """
    if backend != 'hip':
        return 1

    chiplets = common.get_gpu_chiplet_count()
    if chiplets is None:
        return 1

    Config.set('compiler', 'cuda', 'chiplet_number', value=chiplets)
    return chiplets


def chiplet_count(kernelmap_entry: nodes.MapEntry, backend: str, is_persistent: bool, has_dtbmap: bool,
                  extra_grid_dims: List[symbolic.SymbolicType]) -> int:
    """
    Returns the number of chiplets (XCDs on AMD GPUs) the grid of the given kernel is distributed over,
    or 1 if the distribution does not apply to it.

    The distribution pads the first grid dimension to a multiple of the number of chiplets and permutes
    it within itself, leaving the second and third grid dimensions untouched. It therefore applies to
    kernels of any dimensionality, and only steps aside for kernels whose block indices are not
    generated by the kernel scope alone. Kernels whose map has the
    ``allow_chiplet_threadblock_distribution`` property set to False are left alone as well.

    The number of chiplets comes from the ``compiler.cuda.chiplet_number`` configuration entry, whose
    default of 0 means that it is detected automatically (see :func:`detected_chiplet_count`).

    :param kernelmap_entry: Entry node of the kernel map.
    :param backend: GPU backend the code is generated for, ``'cuda'`` or ``'hip'``.
    :param is_persistent: Whether the kernel uses a persistent grid.
    :param has_dtbmap: Whether the kernel contains a dynamic thread-block map.
    :param extra_grid_dims: Grid dimensions contributed by nested device maps, if any.
    """
    chiplets = int(Config.get('compiler', 'cuda', 'chiplet_number'))
    if chiplets < 0:
        raise ValueError(f'Invalid number of chiplets ({chiplets}) configured. Modify the '
                         '`compiler.cuda.chiplet_number` configuration entry to a positive number, or to 0 '
                         'to detect the number of chiplets of the GPU automatically.')

    # A kernel that opts out of the distribution is left alone without any diagnostics, and without
    # querying the GPU for the number of its chiplets
    if not kernelmap_entry.map.allow_chiplet_threadblock_distribution:
        return 1

    if chiplets == 0:
        chiplets = detected_chiplet_count(backend)

    if chiplets == 1:
        return 1

    if backend != 'hip':
        warnings.warn(f'`compiler.cuda.chiplet_number` is set to {chiplets}, but the "{backend}" backend '
                      'targets GPUs without chiplets. Distributing the grid over chiplets relies on the '
                      'round-robin thread-block scheduling of multi-chiplet AMD GPUs.')

    skip_reason: Optional[str] = None
    if is_persistent:
        skip_reason = 'it uses a persistent grid'
    elif has_dtbmap:
        skip_reason = 'it contains a dynamic thread-block map'
    elif extra_grid_dims:
        skip_reason = 'it contains nested device maps'

    if skip_reason is not None:
        warnings.warn(f'Not distributing the grid of kernel "{kernelmap_entry.map.label}" over {chiplets} '
                      f'chiplets because {skip_reason}.')
        return 1

    return chiplets


def distribute_grid_over_chiplets(kernel_label: str, grid_size: List[symbolic.SymbolicType],
                                  chiplets: int) -> Tuple[List[symbolic.SymbolicType], symbolic.SymbolicType]:
    """
    Pads the first dimension of ``grid_size`` to a multiple of ``chiplets`` and returns the padded grid
    together with the number of thread-blocks of that dimension every chiplet owns.

    The hardware dispatches thread-block ``f`` to chiplet ``f % chiplets`` in a round-robin fashion, and
    the flattened block index is ``blockIdx.x + blockIdx.y * gridDim.x + blockIdx.z * gridDim.x *
    gridDim.y``. Padding ``gridDim.x`` to a multiple of the number of chiplets makes the two trailing
    terms vanish modulo that number, so the chiplet of a block is ``blockIdx.x % chiplets`` regardless of
    ``blockIdx.y`` and ``blockIdx.z``, which the distribution therefore leaves untouched. Each chiplet
    receives a contiguous chunk of ``ceil(grid_size[0] / chiplets)`` blocks of the first dimension
    (see :func:`permuted_block_index`), together with the whole of the other dimensions.

    :param kernel_label: Label of the kernel map, for the ``debugprint`` diagnostic.
    :param grid_size: Grid the kernel would be launched with without the distribution.
    :param chiplets: Number of chiplets to distribute over, greater than 1.
    :returns: The padded grid, and the chunk of the first dimension one chiplet owns.
    """
    chunk = symbolic.int_ceil(grid_size[0], chiplets)
    distributed = [chunk * chiplets] + list(grid_size[1:])
    if Config.get_bool('debugprint'):
        print(f'Distributing the grid of kernel "{kernel_label}" over {chiplets} chiplets, adjusting its size '
              f'from {grid_size} to {distributed}.')
    return distributed, chunk


def permuted_block_index(chiplets: int, chunk_cpp: str) -> str:
    """
    Returns the C++ expression the distributed first grid dimension is indexed by.

    Contiguous partitioning: the chiplet of a block is ``blockIdx.x % chiplets`` and its slot within that
    chiplet is ``blockIdx.x / chiplets``, so chiplet k owns the blocks ``[k * chunk .. (k + 1) * chunk - 1]``
    of this dimension.

    :param chiplets: Number of chiplets the grid is distributed over, greater than 1.
    :param chunk_cpp: Chunk returned by :func:`distribute_grid_over_chiplets`, rendered as C++.
    """
    return f'((blockIdx.x % {chiplets}) * {chunk_cpp} + blockIdx.x / {chiplets})'


def trailing_block_condition(index_variable: str, exclusive_bound_cpp: str) -> str:
    """
    Returns the C++ condition masking out the thread-blocks the padding adds beyond the map range.

    The grid of the distributed dimension is padded to a multiple of the number of chiplets, so its
    trailing blocks always have to be masked out, whatever the code generator concludes about the
    other dimensions.

    :param index_variable: Map parameter the distributed dimension is bound to.
    :param exclusive_bound_cpp: One past the last value of that parameter, rendered as C++.
    """
    return f'{index_variable} < {exclusive_bound_cpp}'
