# Copyright 2019-2026 ETH Zurich and the DaCe authors. All rights reserved.
"""
AI-generated implementations for DaCe library nodes.

This library provides two things:

1. The reserved ``'ai'`` implementation, available on **every** library node -- including ones
   defined outside DaCe. Expanding with it asks a language model to write the replacement tasklet,
   given the node's context in the SDFG and on the local machine. See
   :mod:`dace.libraries.ai.expansion`.
2. :class:`~dace.libraries.ai.nodes.ai_node.AINode`, a library node that carries only a
   natural-language description, for microkernels that have no library node of their own. In the
   Python frontend it is written as ``dace.ai('...', a=A, b=B)`` -- see
   :func:`dace.frontend.python.interface.ai` and ``samples/ai``.

The model is reached through a provider selected by the ``ai.provider`` configuration entry; its
SDK is imported lazily, so nothing here requires one to be installed until an expansion actually
runs.
"""

from dace.library import register_library
from dace.sdfg.nodes import AI_IMPLEMENTATION_NAME

from .expansion import ExpandAI
from .exceptions import AIExpansionError
from .nodes import AINode, AITasklet
from .iterate import refine, history, rollback, show, pin, unpin, sessions
from .diagnose import build, repair

# Re-register environments generated by earlier sessions, so that an SDFG expanded previously
# still resolves the libraries its tasklets were linked against.
from .environments import load_generated_environments

load_generated_environments()

register_library(__name__, "AI")
