# Copyright 2019-2026 ETH Zurich and the DaCe authors. All rights reserved.
"""
Materialization of DaCe library environments requested by an AI model.

:func:`dace.library.environment` reads ``inspect.getmodule(env).__file__`` in order to resolve
relative header and CMake file paths, which rules out classes created on the fly with ``type()``.
Instead, an :class:`~dace.libraries.ai.backend.EnvironmentSpec` is rendered into a real Python
module, written to the directory named by ``ai.environment_dir``, and imported. That also means a
generated environment survives the process that produced it: :func:`load_generated_environments`
re-imports the directory when :mod:`dace.libraries.ai` is first imported, so an SDFG expanded in an
earlier session still compiles. The generated modules are plain text and are meant to be read and
edited.
"""

import importlib.util
import logging
import os
import re
import sys
from typing import List, Optional

from dace.config import Config
from dace.libraries.ai.backend import EnvironmentSpec
from dace.libraries.ai.exceptions import AIExpansionError

logger = logging.getLogger(__name__)

#: Prefix of every generated environment module, used to recognize them on reload.
MODULE_PREFIX = 'dace_ai_env_'

_MODULE_TEMPLATE = '''\
# Copyright 2019-2026 ETH Zurich and the DaCe authors. All rights reserved.
"""
DaCe library environment generated by the 'ai' library node expansion.

This file was written automatically so that the environment can be resolved again in later
sessions. It is safe to read, edit, or delete: deleting it only breaks SDFGs whose tasklets still
reference this environment.
"""

import dace.library


@dace.library.environment
class {classname}:

    cmake_minimum_version = {cmake_minimum_version!r}
    cmake_packages = {cmake_packages!r}
    cmake_variables = {cmake_variables!r}
    cmake_includes = {cmake_includes!r}
    cmake_libraries = {cmake_libraries!r}
    cmake_compile_flags = {cmake_compile_flags!r}
    cmake_link_flags = {cmake_link_flags!r}
    cmake_files = []

    headers = {headers!r}
    state_fields = {state_fields!r}
    init_code = {init_code!r}
    finalize_code = {finalize_code!r}
    dependencies = []
'''


def environment_dir(create: bool = False) -> str:
    """
    Returns the directory holding generated environment modules.

    :param create: If True, the directory is created when it does not exist. Reading callers
                   should leave this False so that merely importing DaCe does not create it.
    :return: An absolute path. Defaults to ``~/.dace/ai_environments`` when
             ``ai.environment_dir`` is empty.
    """
    configured = Config.get('ai', 'environment_dir')
    path = os.path.expanduser(os.path.expandvars(configured)) if configured else os.path.join(
        os.path.expanduser('~'), '.dace', 'ai_environments')
    if create:
        os.makedirs(path, exist_ok=True)
    return path


def _sanitize(name: str) -> str:
    """
    Turns a model-supplied environment name into a valid Python identifier.

    :param name: The requested name.
    :return: A safe class-name suffix.
    """
    cleaned = re.sub(r'\W+', '_', name).strip('_')
    if not cleaned or cleaned[0].isdigit():
        cleaned = f'env_{cleaned}'
    return cleaned


def render_environment(spec: EnvironmentSpec) -> str:
    """
    Renders an environment specification as the source of a Python module.

    Every field is emitted as a literal, so the generated module contains no executable logic
    beyond the ``@dace.library.environment`` decoration itself.

    :param spec: The environment requested by the model.
    :return: The module source.
    """
    return _MODULE_TEMPLATE.format(classname=_sanitize(spec.name),
                                   cmake_minimum_version=spec.cmake_minimum_version,
                                   cmake_packages=list(spec.cmake_packages),
                                   cmake_variables=dict(spec.cmake_variables),
                                   cmake_includes=list(spec.cmake_includes),
                                   cmake_libraries=list(spec.cmake_libraries),
                                   cmake_compile_flags=list(spec.cmake_compile_flags),
                                   cmake_link_flags=list(spec.cmake_link_flags),
                                   headers=list(spec.headers),
                                   state_fields=list(spec.state_fields),
                                   init_code=spec.init_code,
                                   finalize_code=spec.finalize_code)


def _import_module(path: str):
    """
    Imports a generated environment module from a file path.

    :param path: Absolute path of the module.
    :return: The imported module.
    :raises AIExpansionError: If the module cannot be imported.
    """
    module_name = os.path.splitext(os.path.basename(path))[0]
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise AIExpansionError(f'Could not load the generated environment module at {path}.')
    module = importlib.util.module_from_spec(spec)
    # Registered in sys.modules before execution so that the environment's full class path, which
    # dace.library.environment derives from the module name, resolves consistently.
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


def materialize(spec: EnvironmentSpec) -> type:
    """
    Writes an environment specification to disk and registers it with DaCe.

    :param spec: The environment requested by the model.
    :return: The registered environment class.
    :raises AIExpansionError: If the environment cannot be written or imported.
    """
    classname = _sanitize(spec.name)
    directory = environment_dir(create=True)
    path = os.path.join(directory, f'{MODULE_PREFIX}{classname.lower()}.py')
    source = render_environment(spec)

    existing = None
    if os.path.exists(path):
        with open(path, 'r') as fp:
            existing = fp.read()
    if existing != source:
        with open(path, 'w') as fp:
            fp.write(source)

    module = _import_module(path)
    env = getattr(module, classname, None)
    if env is None:
        raise AIExpansionError(f'The generated environment module {path} does not define {classname}.')
    logger.info('AI expansion registered environment %s (libraries: %s, headers: %s) from %s', classname,
                ', '.join(spec.cmake_libraries) or 'none', ', '.join(spec.headers) or 'none', path)
    return env


def materialize_all(specs: List[EnvironmentSpec]) -> List[type]:
    """
    Materializes every environment requested for one expansion.

    :param specs: The environments requested by the model.
    :return: The registered environment classes, in the same order.
    """
    return [materialize(spec) for spec in specs]


def resolve_installed(paths: List[str]) -> List[type]:
    """
    Looks up environments the model asked to reuse rather than to define.

    An environment that ships with DaCe already carries the CMake package names, libraries and
    flags that took someone effort to get right, so naming one is both cheaper and more reliable
    than having the model describe the same library from scratch.

    :param paths: Class paths as listed in the prompt, e.g. ``dace.libraries.blas...OpenBLAS``.
    :return: The registered environment classes, in the requested order and without duplicates.
    :raises AIExpansionError: If a requested environment is not registered.
    """
    import dace.library  # Avoid a cyclic import

    resolved: List[type] = []
    for path in paths:
        name = (path or '').strip()
        if not name:
            continue
        try:
            env = dace.library.get_environment(name)
        except KeyError as e:
            registered = ', '.join(sorted(dace.library._DACE_REGISTERED_ENVIRONMENTS)) or 'none'
            error = AIExpansionError(f'The generated code asked to link against the DaCe environment "{name}", '
                                     f'which is not registered. Registered environments: {registered}.')
            error.__cause__ = e
            raise error
        resolved.append(env)
    return _deduplicate(resolved)


def _deduplicate(environments: List[type]) -> List[type]:
    """
    Drops repeated environments, keeping the first occurrence of each.

    Comparison is by class path rather than by identity: re-importing a generated module yields a
    fresh class object that is nevertheless the same environment as far as the code generator,
    which stores these as paths, is concerned.

    :param environments: The environment classes to filter.
    :return: The distinct environments, in their original order.
    """
    seen = set()
    distinct = []
    for env in environments:
        key = env.full_class_path() if hasattr(env, 'full_class_path') else env
        if key in seen:
            continue
        seen.add(key)
        distinct.append(env)
    return distinct


def collect(spec) -> List[type]:
    """
    Resolves every environment one generated tasklet needs.

    :param spec: The specification returned by the model.
    :return: The environment classes to attach to the expansion, reused ones first.
    :raises AIExpansionError: If a reused environment is unknown, or a new one cannot be written.
    """
    return _deduplicate(resolve_installed(spec.use_environments) + materialize_all(spec.environments))


def load_generated_environments(directory: Optional[str] = None) -> List[type]:
    """
    Imports every previously generated environment module so that it is registered again.

    :param directory: The directory to scan. Defaults to :func:`environment_dir`.
    :return: The environment classes that were successfully loaded.
    """
    directory = directory or environment_dir()
    loaded = []
    try:
        entries = sorted(os.listdir(directory))
    except OSError:
        return loaded
    for entry in entries:
        if not entry.startswith(MODULE_PREFIX) or not entry.endswith('.py'):
            continue
        path = os.path.join(directory, entry)
        try:
            module = _import_module(path)
        except Exception:  # A broken or hand-edited module must not break importing DaCe
            logger.warning('Could not load the generated DaCe environment at %s', path, exc_info=True)
            continue
        loaded.extend(value for value in vars(module).values() if getattr(value, '_dace_library_environment', False))
    return loaded
