PROGRAM melting_snow_ice
    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM), PARAMETER  :: KLON = 100
    INTEGER(KIND=JPIM), PARAMETER  :: KLEV = 100
    INTEGER(KIND=JPIM), PARAMETER  :: NCLV = 100

    INTEGER(KIND=JPIM) KIDIA 
    INTEGER(KIND=JPIM) KFDIA 
    INTEGER(KIND=JPIM) NCLDQV 
    INTEGER(KIND=JPIM) NCLDQS 
    INTEGER(KIND=JPIM) NCLDQI 
    INTEGER(KIND=JPIM) NCLDQL 
    INTEGER(KIND=JPIM) NCLDTOP 

    REAL(KIND=JPRB) ZEPSEC
    REAL(KIND=JPRB) RTT
    REAL(KIND=JPRB) PTSPHY
    REAL(KIND=JPRB) ZRLDCP
    REAL(KIND=JPRB) RTAUMEL
    REAL(KIND=JPRB) ZQSICE(KLON, KLEV)
    REAL(KIND=JPRB) ZQXFG(KLON, NCLV)
    REAL(KIND=JPRB) ZTP1(KLON, KLEV)
    REAL(KIND=JPRB) PAP(KLON, KLEV)
    REAL(KIND=JPRB) ZQX(KLON, KLEV, NCLV)

    REAL(KIND=JPRB) ZICETOT(KLON)
    REAL(KIND=JPRB) ZMELTMAX(KLON)

    CALL melting_snow_ice_routine(&
        & KLON, KLEV, NCLV, KIDIA, KFDIA, NCLDQV, NCLDQS, NCLDQI, NCLDQL, NCLDTOP, &
        & ZEPSEC, RTT, PTSPHY, ZRLDCP, RTAUMEL, ZQSICE, ZQXFG, ZTP1, PAP, ZQX, &
        & ZICETOT, ZMELTMAX)

END PROGRAM

SUBROUTINE melting_snow_ice_routine(&
        & KLON, KLEV, NCLV, KIDIA, KFDIA, NCLDQV, NCLDQS, NCLDQI, NCLDQL, NCLDTOP, &
        & ZEPSEC, RTT, PTSPHY, ZRLDCP, RTAUMEL, ZQSICE, ZQXFG, ZTP1, PAP, ZQX, &
        & ZICETOT, ZMELTMAX)

    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM) KLON
    INTEGER(KIND=JPIM) KLEV
    INTEGER(KIND=JPIM) NCLV
    INTEGER(KIND=JPIM) KIDIA 
    INTEGER(KIND=JPIM) KFDIA 
    INTEGER(KIND=JPIM) NCLDQV 
    INTEGER(KIND=JPIM) NCLDQS 
    INTEGER(KIND=JPIM) NCLDQI 
    INTEGER(KIND=JPIM) NCLDQL 
    INTEGER(KIND=JPIM) NCLDTOP 

    REAL(KIND=JPRB) ZEPSEC
    REAL(KIND=JPRB) RTT
    REAL(KIND=JPRB) PTSPHY
    REAL(KIND=JPRB) ZRLDCP
    REAL(KIND=JPRB) RTAUMEL
    REAL(KIND=JPRB) ZQSICE(KLON, KLEV)
    REAL(KIND=JPRB) ZQXFG(KLON, NCLV)
    REAL(KIND=JPRB) ZTP1(KLON, KLEV)
    REAL(KIND=JPRB) PAP(KLON, KLEV)
    REAL(KIND=JPRB) ZQX(KLON, KLEV, NCLV)

    REAL(KIND=JPRB) ZICETOT(KLON)
    REAL(KIND=JPRB) ZMELTMAX(KLON)

    ! temporary variables
    REAL(KIND=JPRB) ZSUBSAT
    REAL(KIND=JPRB) ZTDMTW0
    REAL(KIND=JPRB) ZCONS1

    REAL(KIND=JPRB),PARAMETER :: ZTW1 = 1329.31
    REAL(KIND=JPRB),PARAMETER :: ZTW2 = 0.0074615
    REAL(KIND=JPRB),PARAMETER :: ZTW3 = 0.85E5
    REAL(KIND=JPRB),PARAMETER :: ZTW4 = 40.637
    REAL(KIND=JPRB),PARAMETER :: ZTW5 = 275.0

    DO JK=NCLDTOP,KLEV
        DO JL=KIDIA,KFDIA     ! LOOP CLASS 3

            ZICETOT(JL)=ZQXFG(JL,NCLDQI)+ZQXFG(JL,NCLDQS)
            ZMELTMAX(JL) = 0.0

            ! If there are frozen hydrometeors present and dry-bulb temperature > 0degC
            IF(ZICETOT(JL) > ZEPSEC .AND. ZTP1(JL,JK) > RTT) THEN

                ! Calculate subsaturation
                ZSUBSAT = MAX(ZQSICE(JL,JK)-ZQX(JL,JK,NCLDQV),0.0)

                ! Calculate difference between dry-bulb (ZTP1) and the temperature 
                ! at which the wet-bulb=0degC (RTT-ZSUBSAT*....) using an approx.
                ! Melting only occurs if the wet-bulb temperature >0
                ! i.e. warming of ice particle due to melting > cooling 
                ! due to evaporation.
                ZTDMTW0 = ZTP1(JL,JK)-RTT-ZSUBSAT* &
                        & (ZTW1+ZTW2*(PAP(JL,JK)-ZTW3)-ZTW4*(ZTP1(JL,JK)-ZTW5))
                ! Not implicit yet... 
                ! Ensure ZCONS1 is positive so that ZMELTMAX=0 if ZTDMTW0<0
                ZCONS1 = ABS(PTSPHY*(1.0+0.5*ZTDMTW0)/RTAUMEL)
                ZMELTMAX(JL) = MAX(ZTDMTW0*ZCONS1*ZRLDCP,0.0)
            ENDIF
        ENDDO
    ENDDO

END SUBROUTINE melting_snow_ice_routine
