PROGRAM evaporate_small_liquid_ice

    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM), PARAMETER  :: KLON = 100
    INTEGER(KIND=JPIM), PARAMETER  :: KLEV = 100
    INTEGER(KIND=JPIM), PARAMETER  :: NCLV = 100

    INTEGER(KIND=JPIM) KIDIA 
    INTEGER(KIND=JPIM) KFDIA 
    INTEGER(KIND=JPIM) NCLDQV 
    INTEGER(KIND=JPIM) NCLDQI 
    INTEGER(KIND=JPIM) NCLDQL 
    INTEGER(KIND=JPIM) NCLDTOP 

    REAL(KIND=JPRB) RLMIN
    REAL(KIND=JPRB) ZQX(KLON, KLEV, NCLV)

    REAL(KIND=JPRB) ZSOLQA2(KLON, KLEV, NCLV, NCLV)

    CALL evaporate_small_liquid_ice_routine(&
        & KLON, KLEV, NCLV, KIDIA, KFDIA, NCLDQV, NCLDQI, NCLDQL, NCLDTOP, &
        & RLMIN, ZQX, ZSOLQA2)

END

SUBROUTINE evaporate_small_liquid_ice_routine(&
        & KLON, KLEV, NCLV, KIDIA, KFDIA, NCLDQV, NCLDQI, NCLDQL, NCLDTOP, &
        & RLMIN, ZQX, ZSOLQA2)

    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM) KLON
    INTEGER(KIND=JPIM) KLEV
    INTEGER(KIND=JPIM) NCLV
    INTEGER(KIND=JPIM) KIDIA 
    INTEGER(KIND=JPIM) KFDIA 
    INTEGER(KIND=JPIM) NCLDQV 
    INTEGER(KIND=JPIM) NCLDQI 
    INTEGER(KIND=JPIM) NCLDQL 
    INTEGER(KIND=JPIM) NCLDTOP 

    REAL(KIND=JPRB) RLMIN
    REAL(KIND=JPRB) ZQX(KLON, KLEV, NCLV)

    REAL(KIND=JPRB) ZSOLQA2(KLON, KLEV, NCLV, NCLV)

    DO JK=NCLDTOP,KLEV
        DO JL=KIDIA,KFDIA     ! LOOP CLASS 3

            IF (ZQX(JL,JK,NCLDQL) < RLMIN) THEN
                ZSOLQA2(JL,JK,NCLDQV,NCLDQL) = ZQX(JL,JK,NCLDQL)
                ZSOLQA2(JL,JK,NCLDQL,NCLDQV) = -ZQX(JL,JK,NCLDQL)
            ENDIF

            IF (ZQX(JL,JK,NCLDQI) < RLMIN) THEN
                ZSOLQA2(JL,JK,NCLDQV,NCLDQI) = ZQX(JL,JK,NCLDQI)
                ZSOLQA2(JL,JK,NCLDQI,NCLDQV) = -ZQX(JL,JK,NCLDQI)
            ENDIF

        ENDDO
    ENDDO

END SUBROUTINE evaporate_small_liquid_ice_routine
