PROGRAM fluxes

    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM), PARAMETER  :: KLON = 100
    INTEGER(KIND=JPIM), PARAMETER  :: KLEV = 100

    INTEGER(KIND=JPIM)  :: KIDIA 
    INTEGER(KIND=JPIM)  :: KFDIA 

    REAL(KIND=JPRB) PFSQLF(KLON,KLEV+1)
    REAL(KIND=JPRB) PFSQIF(KLON,KLEV+1)
    REAL(KIND=JPRB) PFCQLNG(KLON,KLEV+1)
    REAL(KIND=JPRB) PFCQNNG(KLON,KLEV+1)
    REAL(KIND=JPRB) PFSQRF(KLON,KLEV+1)
    REAL(KIND=JPRB) PFSQSF(KLON,KLEV+1)
    REAL(KIND=JPRB) PFCQRNG(KLON,KLEV+1)
    REAL(KIND=JPRB) PFCQSNG(KLON,KLEV+1)
    REAL(KIND=JPRB) PFSQLTUR(KLON,KLEV+1)
    REAL(KIND=JPRB) PFSQITUR(KLON,KLEV+1)

    REAL(KIND=JPRB) PVFL(KLON,KLEV)
    REAL(KIND=JPRB) PVFI(KLON,KLEV)
    REAL(KIND=JPRB) PAPH(KLON,KLEV+1)
    REAL(KIND=JPRB) PLUDE(KLON,KLEV) 

    INTEGER(KIND=JPIM), PARAMETER  :: NCLV = 100
    INTEGER(KIND=JPIM)  :: NCLDQL
    INTEGER(KIND=JPIM)  :: NCLDQI
    INTEGER(KIND=JPIM)  :: NCLDQR
    INTEGER(KIND=JPIM)  :: NCLDQS

    REAL(KIND=JPRB) ZQX0(KLON,KLEV,NCLV)
    REAL(KIND=JPRB) ZLNEG(KLON,KLEV,NCLV)
    REAL(KIND=JPRB) ZQXN2D(KLON,KLEV,NCLV)
    REAL(KIND=JPRB) ZFOEALFA(KLON,KLEV+1) 

    REAL(KIND=JPRB) ZRG_R, ZQTMST, PTSPHY


    CALL fluxes_routine( &
        & KLON, KLEV, KIDIA, KFDIA, NCLV, NCLDQL, NCLDQI, NCLDQR, NCLDQS, &
        & PFSQLF, PFSQIF, PFCQNNG, PFCQLNG, PFSQRF, PFSQSF, PFCQRNG, PFCQSNG, PFSQLTUR, PFSQITUR, &
        & PVFL, PVFI, PAPH, PLUDE, ZQX0, ZLNEG, ZQXN2D, ZFOEALFA, ZRG_R, ZQTMST, PTSPHY)

END

SUBROUTINE fluxes_routine( &
    & KLON, KLEV, KIDIA, KFDIA, NCLV, NCLDQL, NCLDQI, NCLDQR, NCLDQS, &
    & PFSQLF, PFSQIF, PFCQNNG, PFCQLNG, PFSQRF, PFSQSF, PFCQRNG, PFCQSNG, PFSQLTUR, PFSQITUR, &
    & PVFL, PVFI, PAPH, PLUDE, ZQX0, ZLNEG, ZQXN2D, ZFOEALFA, ZRG_R, ZQTMST, PTSPHY)

    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM)  :: KLON
    INTEGER(KIND=JPIM)  :: KLEV
    INTEGER(KIND=JPIM)  :: KIDIA 
    INTEGER(KIND=JPIM)  :: KFDIA 

    REAL(KIND=JPRB) PFSQLF(KLON,KLEV+1)
    REAL(KIND=JPRB) PFSQIF(KLON,KLEV+1)
    REAL(KIND=JPRB) PFCQLNG(KLON,KLEV+1)
    REAL(KIND=JPRB) PFCQNNG(KLON,KLEV+1)
    REAL(KIND=JPRB) PFSQRF(KLON,KLEV+1)
    REAL(KIND=JPRB) PFSQSF(KLON,KLEV+1)
    REAL(KIND=JPRB) PFCQRNG(KLON,KLEV+1)
    REAL(KIND=JPRB) PFCQSNG(KLON,KLEV+1)
    REAL(KIND=JPRB) PFSQLTUR(KLON,KLEV+1)
    REAL(KIND=JPRB) PFSQITUR(KLON,KLEV+1)

    REAL(KIND=JPRB) PVFL(KLON,KLEV)
    REAL(KIND=JPRB) PVFI(KLON,KLEV)
    REAL(KIND=JPRB) PAPH(KLON,KLEV+1)
    REAL(KIND=JPRB) PLUDE(KLON,KLEV) 

    INTEGER(KIND=JPIM)  :: NCLV
    INTEGER(KIND=JPIM)  :: NCLDQL
    INTEGER(KIND=JPIM)  :: NCLDQI
    INTEGER(KIND=JPIM)  :: NCLDQR
    INTEGER(KIND=JPIM)  :: NCLDQS

    REAL(KIND=JPRB) ZQX0(KLON,KLEV,NCLV)
    REAL(KIND=JPRB) ZLNEG(KLON,KLEV,NCLV)
    REAL(KIND=JPRB) ZQXN2D(KLON,KLEV,NCLV)
    REAL(KIND=JPRB) ZFOEALFA(KLON,KLEV+1) 

    REAL(KIND=JPRB) ZRG_R, ZGDPH_R, ZQTMST, ZALFAW, PTSPHY

    INTEGER(KIND=JPIM)  :: JK, JL

    DO JL=KIDIA,KFDIA
        PFSQLF(JL,1)  = 0.0
        PFSQIF(JL,1)  = 0.0
        PFSQRF(JL,1)  = 0.0
        PFSQSF(JL,1)  = 0.0
        PFCQLNG(JL,1) = 0.0
        PFCQNNG(JL,1) = 0.0
        PFCQRNG(JL,1) = 0.0 !rain
        PFCQSNG(JL,1) = 0.0 !snow
        ! fluxes due to turbulence
        PFSQLTUR(JL,1) = 0.0
        PFSQITUR(JL,1) = 0.0
    ENDDO

    DO JK=1,KLEV
        DO JL=KIDIA,KFDIA

            ZGDPH_R = -ZRG_R*(PAPH(JL,JK+1)-PAPH(JL,JK))*ZQTMST
            PFSQLF(JL,JK+1)  = PFSQLF(JL,JK)
            PFSQIF(JL,JK+1)  = PFSQIF(JL,JK)
            PFSQRF(JL,JK+1)  = PFSQLF(JL,JK)
            PFSQSF(JL,JK+1)  = PFSQIF(JL,JK)
            PFCQLNG(JL,JK+1) = PFCQLNG(JL,JK)
            PFCQNNG(JL,JK+1) = PFCQNNG(JL,JK)
            PFCQRNG(JL,JK+1) = PFCQLNG(JL,JK)
            PFCQSNG(JL,JK+1) = PFCQNNG(JL,JK)
            PFSQLTUR(JL,JK+1) = PFSQLTUR(JL,JK)
            PFSQITUR(JL,JK+1) = PFSQITUR(JL,JK)

            ZALFAW=ZFOEALFA(JL,JK)

            ! Liquid , LS scheme minus detrainment
            PFSQLF(JL,JK+1)=PFSQLF(JL,JK+1)+ &
            &(ZQXN2D(JL,JK,NCLDQL)-ZQX0(JL,JK,NCLDQL)+PVFL(JL,JK)*PTSPHY-ZALFAW*PLUDE(JL,JK))*ZGDPH_R
            ! liquid, negative numbers
            PFCQLNG(JL,JK+1)=PFCQLNG(JL,JK+1)+ZLNEG(JL,JK,NCLDQL)*ZGDPH_R

            ! liquid, vertical diffusion
            PFSQLTUR(JL,JK+1)=PFSQLTUR(JL,JK+1)+PVFL(JL,JK)*PTSPHY*ZGDPH_R

            ! Rain, LS scheme 
            PFSQRF(JL,JK+1)=PFSQRF(JL,JK+1)+(ZQXN2D(JL,JK,NCLDQR)-ZQX0(JL,JK,NCLDQR))*ZGDPH_R 
            ! rain, negative numbers
            PFCQRNG(JL,JK+1)=PFCQRNG(JL,JK+1)+ZLNEG(JL,JK,NCLDQR)*ZGDPH_R

            ! Ice , LS scheme minus detrainment
            PFSQIF(JL,JK+1)=PFSQIF(JL,JK+1)+ &
            & (ZQXN2D(JL,JK,NCLDQI)-ZQX0(JL,JK,NCLDQI)+PVFI(JL,JK)*PTSPHY-(1.0-ZALFAW)*PLUDE(JL,JK))*ZGDPH_R
            ! ice, negative numbers
            PFCQNNG(JL,JK+1)=PFCQNNG(JL,JK+1)+ZLNEG(JL,JK,NCLDQI)*ZGDPH_R

            ! ice, vertical diffusion
            PFSQITUR(JL,JK+1)=PFSQITUR(JL,JK+1)+PVFI(JL,JK)*PTSPHY*ZGDPH_R

            ! snow, LS scheme
            PFSQSF(JL,JK+1)=PFSQSF(JL,JK+1)+(ZQXN2D(JL,JK,NCLDQS)-ZQX0(JL,JK,NCLDQS))*ZGDPH_R 
            ! snow, negative numbers
            PFCQSNG(JL,JK+1)=PFCQSNG(JL,JK+1)+ZLNEG(JL,JK,NCLDQS)*ZGDPH_R
        ENDDO
    ENDDO

END SUBROUTINE fluxes_routine