PROGRAM copy_precipitation_arrays

    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM), PARAMETER  :: KLON = 100
    INTEGER(KIND=JPIM), PARAMETER  :: KLEV = 100
    INTEGER(KIND=JPIM), PARAMETER  :: NCLV = 100

    INTEGER(KIND=JPIM)  :: KIDIA 
    INTEGER(KIND=JPIM)  :: KFDIA
    INTEGER(KIND=JPIM)  :: NCLDQL
    INTEGER(KIND=JPIM)  :: NCLDQI
    INTEGER(KIND=JPIM)  :: NCLDQR
    INTEGER(KIND=JPIM)  :: NCLDQS
    REAL(KIND=JPRB)     :: PFPLSL(KLON,KLEV+1)
    REAL(KIND=JPRB)     :: PFPLSN(KLON,KLEV+1)
    REAL(KIND=JPRB)     :: ZPFPLSX(KLON,KLEV+1,NCLV)

    CALL copy_precipitation_arrays_routine( &
        & KLON, KLEV, KIDIA, KFDIA, NCLV, NCLDQL, NCLDQI, NCLDQR, NCLDQS, &
        & PFPLSL, PFPLSN, ZPFPLSX)

END

SUBROUTINE copy_precipitation_arrays_routine( &
    & KLON, KLEV, KIDIA, KFDIA, NCLV, NCLDQL, NCLDQI, NCLDQR, NCLDQS, &
    & PFPLSL, PFPLSN, ZPFPLSX)

    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM)  :: KLON
    INTEGER(KIND=JPIM)  :: KLEV
    INTEGER(KIND=JPIM)  :: KIDIA 
    INTEGER(KIND=JPIM)  :: KFDIA
    INTEGER(KIND=JPIM)  :: NCLV
    INTEGER(KIND=JPIM)  :: NCLDQL
    INTEGER(KIND=JPIM)  :: NCLDQI
    INTEGER(KIND=JPIM)  :: NCLDQR
    INTEGER(KIND=JPIM)  :: NCLDQS
    REAL(KIND=JPRB)     :: PFPLSL(KLON,KLEV+1)
    REAL(KIND=JPRB)     :: PFPLSN(KLON,KLEV+1)
    REAL(KIND=JPRB)     :: ZPFPLSX(KLON,KLEV+1,NCLV)

    INTEGER(KIND=JPIM)  :: JK, JL

    DO JK=1,KLEV+1
        DO JL=KIDIA,KFDIA
          PFPLSL(JL,JK) = ZPFPLSX(JL,JK,NCLDQR)+ZPFPLSX(JL,JK,NCLDQL)
          PFPLSN(JL,JK) = ZPFPLSX(JL,JK,NCLDQS)+ZPFPLSX(JL,JK,NCLDQI)
        ENDDO
    ENDDO

END SUBROUTINE copy_precipitation_arrays_routine