PROGRAM copy_precipitation_flux

    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    ! Why are these set here again?
    INTEGER(KIND=JPIM), PARAMETER  :: KLON = 100
    INTEGER(KIND=JPIM), PARAMETER  :: KLEV = 100
    INTEGER(KIND=JPIM), PARAMETER  :: NCLV = 100

    INTEGER(KIND=JPIM) KIDIA 
    INTEGER(KIND=JPIM) KFDIA 
    INTEGER(KIND=JPIM) NCLDQR 
    INTEGER(KIND=JPIM) NCLDQS 
    INTEGER(KIND=JPIM) NCLDQL 
    INTEGER(KIND=JPIM) NCLDQI 

    REAL(KIND=JPRB) ZPFPLSX(KLON, KLEV+1, NCLV)

    REAL(KIND=JPRB) PFPLSL(KLON, KLEV+1)
    REAL(KIND=JPRB) PFPLSN(KLON, KLEV+1)

    CALL copy_precipitation_flux_routine(&
        &KLON, KLEV, NCLV, KIDIA, KFDIA, NCLDQR, NCLDQS, NCLDQL, NCLDQI, ZPFPLSX, PFPLSL, PFPLSN)

END PROGRAM

SUBROUTINE copy_precipitation_flux_routine(&
    &KLON, KLEV, NCLV, KIDIA, KFDIA, NCLDQR, NCLDQS, NCLDQL, NCLDQI, ZPFPLSX, PFPLSL, PFPLSN)

    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM) KLON
    INTEGER(KIND=JPIM) KLEV
    INTEGER(KIND=JPIM) NCLV
    INTEGER(KIND=JPIM) KIDIA 
    INTEGER(KIND=JPIM) KFDIA 
    INTEGER(KIND=JPIM) NCLDQR 
    INTEGER(KIND=JPIM) NCLDQS 
    INTEGER(KIND=JPIM) NCLDQL 
    INTEGER(KIND=JPIM) NCLDQI 

    REAL(KIND=JPRB) ZPFPLSX(KLON, KLEV+1, NCLV)

    REAL(KIND=JPRB) PFPLSL(KLON, KLEV+1)
    REAL(KIND=JPRB) PFPLSN(KLON, KLEV+1)

    DO JK=1,KLEV+1
        DO JL=KIDIA,KFDIA
            PFPLSL(JL,JK) = ZPFPLSX(JL,JK,NCLDQR)+ZPFPLSX(JL,JK,NCLDQL)
            PFPLSN(JL,JK) = ZPFPLSX(JL,JK,NCLDQS)+ZPFPLSX(JL,JK,NCLDQI)
        ENDDO
    ENDDO
END SUBROUTINE
