#include <cstdlib>
#include <dace/dace.h>
#include <chrono>
typedef void * CLOUDSCOUTER4Handle_t;
extern "C" CLOUDSCOUTER4Handle_t __dace_init_CLOUDSCOUTER4();
extern "C" void __dace_exit_CLOUDSCOUTER4(CLOUDSCOUTER4Handle_t handle);
extern "C" void __program_CLOUDSCOUTER4(CLOUDSCOUTER4Handle_t handle, int * __restrict__ KTYPE, int * __restrict__ LDCUM, double * __restrict__ PA, double * __restrict__ PAP, double * __restrict__ PAPH, double * __restrict__ PCCN, double * __restrict__ PCLV, double * __restrict__ PCOVPTOT, double * __restrict__ PDYNA, double * __restrict__ PDYNI, double * __restrict__ PDYNL, double * __restrict__ PEXTRA, double * __restrict__ PFCQLNG, double * __restrict__ PFCQNNG, double * __restrict__ PFCQRNG, double * __restrict__ PFCQSNG, double * __restrict__ PFHPSL, double * __restrict__ PFHPSN, double * __restrict__ PFPLSL, double * __restrict__ PFPLSN, double * __restrict__ PFSQIF, double * __restrict__ PFSQITUR, double * __restrict__ PFSQLF, double * __restrict__ PFSQLTUR, double * __restrict__ PFSQRF, double * __restrict__ PFSQSF, double * __restrict__ PHRLW, double * __restrict__ PHRSW, double * __restrict__ PICRIT_AER, double * __restrict__ PLCRIT_AER, double * __restrict__ PLSM, double * __restrict__ PLU, double * __restrict__ PLUDE, double * __restrict__ PMFD, double * __restrict__ PMFU, double * __restrict__ PNICE, double * __restrict__ PQ, double * __restrict__ PRAINFRAC_TOPRFZ, double * __restrict__ PRE_ICE, double * __restrict__ PSNDE, double * __restrict__ PSUPSAT, double * __restrict__ PT, double * __restrict__ PVERVEL, double * __restrict__ PVFA, double * __restrict__ PVFI, double * __restrict__ PVFL, double * __restrict__ tendency_cml_T, double * __restrict__ tendency_cml_a, double * __restrict__ tendency_cml_cld, double * __restrict__ tendency_cml_q, double * __restrict__ tendency_loc_T, double * __restrict__ tendency_loc_a, double * __restrict__ tendency_loc_cld, double * __restrict__ tendency_loc_q, double * __restrict__ tendency_tmp_T, double * __restrict__ tendency_tmp_a, double * __restrict__ tendency_tmp_cld, double * __restrict__ tendency_tmp_q, int LAERICEAUTO, int LAERICESED, int LAERLIQAUTOLSP, int LAERLIQCOLL, int LDMAINCALL, int LDSLPHY, int NSSOPT, double PTSPHY, double R2ES, double R3IES, double R3LES, double R4IES, double R4LES, double R5ALSCP, double R5ALVCP, double R5IES, double R5LES, double RALFDCP, double RALSDCP, double RALVDCP, double RAMID, double RAMIN, double RCCN, double RCLCRIT_LAND, double RCLCRIT_SEA, double RCLDIFF, double RCLDIFF_CONVI, double RCLDTOPCF, double RCL_APB1, double RCL_APB2, double RCL_APB3, double RCL_CDENOM1, double RCL_CDENOM2, double RCL_CDENOM3, double RCL_CONST1I, double RCL_CONST1R, double RCL_CONST1S, double RCL_CONST2I, double RCL_CONST2R, double RCL_CONST2S, double RCL_CONST3I, double RCL_CONST3R, double RCL_CONST3S, double RCL_CONST4I, double RCL_CONST4R, double RCL_CONST4S, double RCL_CONST5I, double RCL_CONST5R, double RCL_CONST5S, double RCL_CONST6I, double RCL_CONST6R, double RCL_CONST6S, double RCL_CONST7S, double RCL_CONST8S, double RCL_FAC1, double RCL_FAC2, double RCL_FZRAB, double RCL_KA273, double RCL_KKAac, double RCL_KKAau, double RCL_KKBac, double RCL_KKBaun, double RCL_KKBauq, double RCL_KK_CLOUD_NUM_LAND, double RCL_KK_CLOUD_NUM_SEA, double RCOVPMIN, double RCPD, double RD, double RDENSREF, double RDEPLIQREFDEPTH, double RDEPLIQREFRATE, double RETV, double RG, double RICEINIT, double RKCONV, double RKOOP1, double RKOOP2, double RKOOPTAU, double RLCRITSNOW, double RLMIN, double RLMLT, double RLSTT, double RLVTT, double RNICE, double RPECONS, double RPRC1, double RPRECRHMAX, double RSNOWLIN1, double RSNOWLIN2, double RTAUMEL, double RTHOMO, double RTICE, double RTICECU, double RTT, double RTWAT, double RTWAT_RTICECU_R, double RTWAT_RTICE_R, double RV, double RVICE, double RVRAIN, double RVRFACTOR, double RVSNOW);

void cloudsc2_internal(int * __restrict__ KTYPE, int * __restrict__ LDCUM, double * __restrict__ PA, double * __restrict__ PAP, double * __restrict__ PAPH, double * __restrict__ PCCN, double * __restrict__ PCLV, double * __restrict__ PCOVPTOT, double * __restrict__ PDYNA, double * __restrict__ PDYNI, double * __restrict__ PDYNL, double * __restrict__ PEXTRA, double * __restrict__ PFCQLNG, double * __restrict__ PFCQNNG, double * __restrict__ PFCQRNG, double * __restrict__ PFCQSNG, double * __restrict__ PFHPSL, double * __restrict__ PFHPSN, double * __restrict__ PFPLSL, double * __restrict__ PFPLSN, double * __restrict__ PFSQIF, double * __restrict__ PFSQITUR, double * __restrict__ PFSQLF, double * __restrict__ PFSQLTUR, double * __restrict__ PFSQRF, double * __restrict__ PFSQSF, double * __restrict__ PHRLW, double * __restrict__ PHRSW, double * __restrict__ PICRIT_AER, double * __restrict__ PLCRIT_AER, double * __restrict__ PLSM, double * __restrict__ PLU, double * __restrict__ PLUDE, double * __restrict__ PMFD, double * __restrict__ PMFU, double * __restrict__ PNICE, double * __restrict__ PQ, double * __restrict__ PRAINFRAC_TOPRFZ, double * __restrict__ PRE_ICE, double * __restrict__ PSNDE, double * __restrict__ PSUPSAT, double * __restrict__ PT, double * __restrict__ PVERVEL, double * __restrict__ PVFA, double * __restrict__ PVFI, double * __restrict__ PVFL, double * __restrict__ tendency_cml_T, double * __restrict__ tendency_cml_a, double * __restrict__ tendency_cml_cld, double * __restrict__ tendency_cml_q, double * __restrict__ tendency_loc_T, double * __restrict__ tendency_loc_a, double * __restrict__ tendency_loc_cld, double * __restrict__ tendency_loc_q, double * __restrict__ tendency_tmp_T, double * __restrict__ tendency_tmp_a, double * __restrict__ tendency_tmp_cld, double * __restrict__ tendency_tmp_q, int LAERICEAUTO, int LAERICESED, int LAERLIQAUTOLSP, int LAERLIQCOLL, int LDMAINCALL, int LDSLPHY, int NSSOPT, double PTSPHY, double R2ES, double R3IES, double R3LES, double R4IES, double R4LES, double R5ALSCP, double R5ALVCP, double R5IES, double R5LES, double RALFDCP, double RALSDCP, double RALVDCP, double RAMID, double RAMIN, double RCCN, double RCLCRIT_LAND, double RCLCRIT_SEA, double RCLDIFF, double RCLDIFF_CONVI, double RCLDTOPCF, double RCL_APB1, double RCL_APB2, double RCL_APB3, double RCL_CDENOM1, double RCL_CDENOM2, double RCL_CDENOM3, double RCL_CONST1I, double RCL_CONST1R, double RCL_CONST1S, double RCL_CONST2I, double RCL_CONST2R, double RCL_CONST2S, double RCL_CONST3I, double RCL_CONST3R, double RCL_CONST3S, double RCL_CONST4I, double RCL_CONST4R, double RCL_CONST4S, double RCL_CONST5I, double RCL_CONST5R, double RCL_CONST5S, double RCL_CONST6I, double RCL_CONST6R, double RCL_CONST6S, double RCL_CONST7S, double RCL_CONST8S, double RCL_FAC1, double RCL_FAC2, double RCL_FZRAB, double RCL_KA273, double RCL_KKAac, double RCL_KKAau, double RCL_KKBac, double RCL_KKBaun, double RCL_KKBauq, double RCL_KK_CLOUD_NUM_LAND, double RCL_KK_CLOUD_NUM_SEA, double RCOVPMIN, double RCPD, double RD, double RDENSREF, double RDEPLIQREFDEPTH, double RDEPLIQREFRATE, double RETV, double RG, double RICEINIT, double RKCONV, double RKOOP1, double RKOOP2, double RKOOPTAU, double RLCRITSNOW, double RLMIN, double RLMLT, double RLSTT, double RLVTT, double RNICE, double RPECONS, double RPRC1, double RPRECRHMAX, double RSNOWLIN1, double RSNOWLIN2, double RTAUMEL, double RTHOMO, double RTICE, double RTICECU, double RTT, double RTWAT, double RTWAT_RTICECU_R, double RTWAT_RTICE_R, double RV, double RVICE, double RVRAIN, double RVRFACTOR, double RVSNOW)
{
    CLOUDSCOUTER4Handle_t handle;
    handle = __dace_init_CLOUDSCOUTER4();
    auto start = std::chrono::high_resolution_clock::now();
    __program_CLOUDSCOUTER4(handle, KTYPE,LDCUM,PA,PAP,PAPH,PCCN,PCLV,PCOVPTOT,PDYNA,PDYNI,PDYNL,PEXTRA,PFCQLNG,PFCQNNG,PFCQRNG,PFCQSNG,PFHPSL,PFHPSN,PFPLSL,PFPLSN,PFSQIF,PFSQITUR,PFSQLF,PFSQLTUR,PFSQRF,PFSQSF,PHRLW,PHRSW,PICRIT_AER,PLCRIT_AER,PLSM,PLU,PLUDE,PMFD,PMFU,PNICE,PQ,PRAINFRAC_TOPRFZ,PRE_ICE,PSNDE,PSUPSAT,PT,PVERVEL,PVFA,PVFI,PVFL,tendency_cml_T,tendency_cml_a,tendency_cml_cld,tendency_cml_q,tendency_loc_T,tendency_loc_a,tendency_loc_cld,tendency_loc_q,tendency_tmp_T,tendency_tmp_a,tendency_tmp_cld,tendency_tmp_q,LAERICEAUTO,LAERICESED,LAERLIQAUTOLSP,LAERLIQCOLL,LDMAINCALL,LDSLPHY,NSSOPT,PTSPHY,R2ES,R3IES,R3LES,R4IES,R4LES,R5ALSCP,R5ALVCP,R5IES,R5LES,RALFDCP,RALSDCP,RALVDCP,RAMID,RAMIN,RCCN,RCLCRIT_LAND,RCLCRIT_SEA,RCLDIFF,RCLDIFF_CONVI,RCLDTOPCF,RCL_APB1,RCL_APB2,RCL_APB3,RCL_CDENOM1,RCL_CDENOM2,RCL_CDENOM3,RCL_CONST1I,RCL_CONST1R,RCL_CONST1S,RCL_CONST2I,RCL_CONST2R,RCL_CONST2S,RCL_CONST3I,RCL_CONST3R,RCL_CONST3S,RCL_CONST4I,RCL_CONST4R,RCL_CONST4S,RCL_CONST5I,RCL_CONST5R,RCL_CONST5S,RCL_CONST6I,RCL_CONST6R,RCL_CONST6S,RCL_CONST7S,RCL_CONST8S,RCL_FAC1,RCL_FAC2,RCL_FZRAB,RCL_KA273,RCL_KKAac,RCL_KKAau,RCL_KKBac,RCL_KKBaun,RCL_KKBauq,RCL_KK_CLOUD_NUM_LAND,RCL_KK_CLOUD_NUM_SEA,RCOVPMIN,RCPD,RD,RDENSREF,RDEPLIQREFDEPTH,RDEPLIQREFRATE,RETV,RG,RICEINIT,RKCONV,RKOOP1,RKOOP2,RKOOPTAU,RLCRITSNOW,RLMIN,RLMLT,RLSTT,RLVTT,RNICE,RPECONS,RPRC1,RPRECRHMAX,RSNOWLIN1,RSNOWLIN2,RTAUMEL,RTHOMO,RTICE,RTICECU,RTT,RTWAT,RTWAT_RTICECU_R,RTWAT_RTICE_R,RV,RVICE,RVRAIN,RVRFACTOR,RVSNOW);
    auto end = std::chrono::high_resolution_clock::now();
    printf("Time %d [ms]\n", std::chrono::duration_cast<std::chrono::milliseconds>(end-start).count());
    __dace_exit_CLOUDSCOUTER4(handle);
}
DACE_EXPORTED void cloudsc2_(int * __restrict__ KTYPE, 
int * __restrict__ LDCUM, 
double * __restrict__ PA, 
double * __restrict__ PAP, 
double * __restrict__ PAPH, 
double * __restrict__ PCCN, 
double * __restrict__ PCLV, 
double * __restrict__ PCOVPTOT, 
double * __restrict__ PDYNA, 
double * __restrict__ PDYNI, 
double * __restrict__ PDYNL, 
double * __restrict__ PEXTRA, 
double * __restrict__ PFCQLNG, 
double * __restrict__ PFCQNNG, 
double * __restrict__ PFCQRNG, 
double * __restrict__ PFCQSNG, 
double * __restrict__ PFHPSL, 
double * __restrict__ PFHPSN, 
double * __restrict__ PFPLSL, 
double * __restrict__ PFPLSN, 
double * __restrict__ PFSQIF, 
double * __restrict__ PFSQITUR, 
double * __restrict__ PFSQLF, 
double * __restrict__ PFSQLTUR, 
double * __restrict__ PFSQRF, 
double * __restrict__ PFSQSF, 
double * __restrict__ PHRLW, 
double * __restrict__ PHRSW, 
double * __restrict__ PICRIT_AER, 
double * __restrict__ PLCRIT_AER, 
double * __restrict__ PLSM, 
double * __restrict__ PLU, 
double * __restrict__ PLUDE, 
double * __restrict__ PMFD, 
double * __restrict__ PMFU, 
double * __restrict__ PNICE, 
double * __restrict__ PQ, 
double * __restrict__ PRAINFRAC_TOPRFZ, 
double * __restrict__ PRE_ICE, 
double * __restrict__ PSNDE, 
double * __restrict__ PSUPSAT, 
double * __restrict__ PT, 
double * __restrict__ PVERVEL, 
double * __restrict__ PVFA, 
double * __restrict__ PVFI, 
double * __restrict__ PVFL, 
double * __restrict__ tendency_cml_T, 
double * __restrict__ tendency_cml_a, 
double * __restrict__ tendency_cml_cld, 
double * __restrict__ tendency_cml_q, 
double * __restrict__ tendency_loc_T, 
double * __restrict__ tendency_loc_a, 
double * __restrict__ tendency_loc_cld, 
double * __restrict__ tendency_loc_q, 
double * __restrict__ tendency_tmp_T, 
double * __restrict__ tendency_tmp_a, 
double * __restrict__ tendency_tmp_cld, 
double * __restrict__ tendency_tmp_q,  int * LAERICEAUTO, int * LAERICESED, int * LAERLIQAUTOLSP, int * LAERLIQCOLL, int * LDMAINCALL, int * LDSLPHY, int * NSSOPT, double * PTSPHY, double * R2ES, double * R3IES, double * R3LES, double * R4IES, double * R4LES, double * R5ALSCP, double * R5ALVCP, double * R5IES, double * R5LES, double * RALFDCP, double * RALSDCP, double * RALVDCP, double * RAMID, double * RAMIN, double * RCCN, double * RCLCRIT_LAND, double * RCLCRIT_SEA, double * RCLDIFF, double * RCLDIFF_CONVI, double * RCLDTOPCF, double * RCL_APB1, double * RCL_APB2, double * RCL_APB3, double * RCL_CDENOM1, double * RCL_CDENOM2, double * RCL_CDENOM3, double * RCL_CONST1I, double * RCL_CONST1R, double * RCL_CONST1S, double * RCL_CONST2I, double * RCL_CONST2R, double * RCL_CONST2S, double * RCL_CONST3I, double * RCL_CONST3R, double * RCL_CONST3S, double * RCL_CONST4I, double * RCL_CONST4R, double * RCL_CONST4S, double * RCL_CONST5I, double * RCL_CONST5R, double * RCL_CONST5S, double * RCL_CONST6I, double * RCL_CONST6R, double * RCL_CONST6S, double * RCL_CONST7S, double * RCL_CONST8S, double * RCL_FAC1, double * RCL_FAC2, double * RCL_FZRAB, double * RCL_KA273, double * RCL_KKAac, double * RCL_KKAau, double * RCL_KKBac, double * RCL_KKBaun, double * RCL_KKBauq, double * RCL_KK_CLOUD_NUM_LAND, double * RCL_KK_CLOUD_NUM_SEA, double * RCOVPMIN, double * RCPD, double * RD, double * RDENSREF, double * RDEPLIQREFDEPTH, double * RDEPLIQREFRATE, double * RETV, double * RG, double * RICEINIT, double * RKCONV, double * RKOOP1, double * RKOOP2, double * RKOOPTAU, double * RLCRITSNOW, double * RLMIN, double * RLMLT, double * RLSTT, double * RLVTT, double * RNICE, double * RPECONS, double * RPRC1, double * RPRECRHMAX, double * RSNOWLIN1, double * RSNOWLIN2, double * RTAUMEL, double * RTHOMO, double * RTICE, double * RTICECU, double * RTT, double * RTWAT, double * RTWAT_RTICECU_R, double * RTWAT_RTICE_R, double * RV, double * RVICE, double * RVRAIN, double * RVRFACTOR, double * RVSNOW)
{
    cloudsc2_internal(KTYPE,
LDCUM,
PA,
PAP,
PAPH,
PCCN,
PCLV,
PCOVPTOT,
PDYNA,
PDYNI,
PDYNL,
PEXTRA,
PFCQLNG,
PFCQNNG,
PFCQRNG,
PFCQSNG,
PFHPSL,
PFHPSN,
PFPLSL,
PFPLSN,
PFSQIF,
PFSQITUR,
PFSQLF,
PFSQLTUR,
PFSQRF,
PFSQSF,
PHRLW,
PHRSW,
PICRIT_AER,
PLCRIT_AER,
PLSM,
PLU,
PLUDE,
PMFD,
PMFU,
PNICE,
PQ,
PRAINFRAC_TOPRFZ,
PRE_ICE,
PSNDE,
PSUPSAT,
PT,
PVERVEL,
PVFA,
PVFI,
PVFL,
tendency_cml_T,
tendency_cml_a,
tendency_cml_cld,
tendency_cml_q,
tendency_loc_T,
tendency_loc_a,
tendency_loc_cld,
tendency_loc_q,
tendency_tmp_T,
tendency_tmp_a,
tendency_tmp_cld,
tendency_tmp_q, *LAERICEAUTO, *LAERICESED, *LAERLIQAUTOLSP, *LAERLIQCOLL, *LDMAINCALL, *LDSLPHY, *NSSOPT, *PTSPHY, *R2ES, *R3IES, *R3LES, *R4IES, *R4LES, *R5ALSCP, *R5ALVCP, *R5IES, *R5LES, *RALFDCP, *RALSDCP, *RALVDCP, *RAMID, *RAMIN, *RCCN, *RCLCRIT_LAND, *RCLCRIT_SEA, *RCLDIFF, *RCLDIFF_CONVI, *RCLDTOPCF, *RCL_APB1, *RCL_APB2, *RCL_APB3, *RCL_CDENOM1, *RCL_CDENOM2, *RCL_CDENOM3, *RCL_CONST1I, *RCL_CONST1R, *RCL_CONST1S, *RCL_CONST2I, *RCL_CONST2R, *RCL_CONST2S, *RCL_CONST3I, *RCL_CONST3R, *RCL_CONST3S, *RCL_CONST4I, *RCL_CONST4R, *RCL_CONST4S, *RCL_CONST5I, *RCL_CONST5R, *RCL_CONST5S, *RCL_CONST6I, *RCL_CONST6R, *RCL_CONST6S, *RCL_CONST7S, *RCL_CONST8S, *RCL_FAC1, *RCL_FAC2, *RCL_FZRAB, *RCL_KA273, *RCL_KKAac, *RCL_KKAau, *RCL_KKBac, *RCL_KKBaun, *RCL_KKBauq, *RCL_KK_CLOUD_NUM_LAND, *RCL_KK_CLOUD_NUM_SEA, *RCOVPMIN, *RCPD, *RD, *RDENSREF, *RDEPLIQREFDEPTH, *RDEPLIQREFRATE, *RETV, *RG, *RICEINIT, *RKCONV, *RKOOP1, *RKOOP2, *RKOOPTAU, *RLCRITSNOW, *RLMIN, *RLMLT, *RLSTT, *RLVTT, *RNICE, *RPECONS, *RPRC1, *RPRECRHMAX, *RSNOWLIN1, *RSNOWLIN2, *RTAUMEL, *RTHOMO, *RTICE, *RTICECU, *RTT, *RTWAT, *RTWAT_RTICECU_R, *RTWAT_RTICE_R, *RV, *RVICE, *RVRAIN, *RVRFACTOR, *RVSNOW);
}
