include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

variables:
  PY_VERSION: '3.13'
  CUDA_VERSION: '12.9.1'
  UBUNTU_VERSION: '24.04'

stages:
  - build
  - test

build_cscs_gh200:
  stage: build
  extends:
    - .dynamic-image-name # Creates a tag (exported as DOCKER_TAG) depending on the files in WATCH_FILECHANGES
    - .container-builder-cscs-gh200
  variables:
    BASE_IMAGE: jfrog.svc.cscs.ch/dockerhub/nvidia/cuda:${CUDA_VERSION}-devel-ubuntu${UBUNTU_VERSION}
    CSCS_REBUILD_POLICY: if-not-exists
    DOCKERFILE: ci/Dockerfile
    DOCKER_BUILD_ARGS: '["BASE_IMAGE", "PY_VERSION", "WORKDIR_PATH"]'
    PERSIST_IMAGE_NAME: ${CSCS_REGISTRY_PATH}/public/dace-gpu  # The $DOCKER_TAG tag is added in the before_script of .dynamic-image-name
    WATCH_FILECHANGES: 'ci/Dockerfile ci/cscs_gpu.yml'
  needs: []

test_cscs_gh200:
  stage: test
  extends:
    - .container-runner-daint-gh200
  image: ${CSCS_REGISTRY_PATH}/public/dace-gpu:${DOCKER_TAG}
  variables:
    TEST_VARIANTS: 'gpu'
    CSCS_CUDA_MPS: 1
    SLURM_GPUS_PER_NODE: 4
    SLURM_JOB_NUM_NODES: 1
    SLURM_TIMELIMIT: 60
    PYTEST_XDIST_AUTO_NUM_WORKERS: 32
  needs:
    - build_cscs_gh200
  script:
    # Since the image does not contain the repo, we need to clone it before running the tests.
    # The output folder is inside the docker image (${WORKDIR}/dace), so it won't take up
    # space on $SCRATCH but in a ephemeral tmpfs mount in the running node.
    - mkdir -p "${WORKDIR}/dace" && git clone --recursive "${CSCS_CI_ORIG_CLONE_URL}" "${WORKDIR}/dace"
    - cd "${WORKDIR}/dace"
    - git checkout "${CI_COMMIT_SHA}"
    - uv pip install -e ".[testing]"
    - export DACE_cache=unique
    - pytest --cov-report=xml --cov=dace --tb=short --timeout_method thread --timeout=300 -n 32 -m "${TEST_VARIANTS}"
    - export COVERAGE_RCFILE=`pwd`/.coveragerc
    - export PYTHON_BINARY="coverage run --source=dace --parallel-mode"
    - ./tests/cuda_test.sh
    - coverage combine . */; coverage report; coverage xml
    - reachable=0
    - ping -W 2 -c 1 codecov.io || reachable=$?
    - if [ $reachable -eq 0 ]; then
    -   ./codecov
    - else
    -   echo "Codecov.io is unreachable"
    - fi
