from dace.optimization.cutout_tuning.spaces.data_layout_space import DataLayoutSpace
from dace.optimization.cutout_tuning.spaces.map_permutation_space import MapPermutationSpace
from dace.optimization.cutout_tuning.spaces.map_tiling_space import MapTilingSpace