!Flipped arrrays and caching and no ZSOLQA computation
PROGRAM vert_loop_7_2


    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM), PARAMETER  :: KLON = 100
    INTEGER(KIND=JPIM), PARAMETER  :: KLEV = 100
    INTEGER(KIND=JPIM), PARAMETER  :: NCLV = 10
    INTEGER(KIND=JPIM), PARAMETER  :: NBLOCKS = 100

    ! Parameters
    INTEGER(KIND=JPIM), PARAMETER :: NCLDQS = 6
    INTEGER(KIND=JPIM), PARAMETER :: NCLDQI = 3
    INTEGER(KIND=JPIM), PARAMETER :: NCLDQL = 4
    INTEGER(KIND=JPIM), PARAMETER :: NCLDTOP = 2

    ! input
    REAL(KIND=JPRB) PTSPHY
    REAL(KIND=JPRB) RLMIN
    REAL(KIND=JPRB) ZEPSEC
    REAL(KIND=JPRB) RG
    REAL(KIND=JPRB) PLU(NBLOCKS, KLON, KLEV)
    LOGICAL LDCUM(NBLOCKS, KLON)
    REAL(KIND=JPRB) PAPH(NBLOCKS, KLON, KLEV+1)

    ! output
    REAL(KIND=JPRB) PLUDE(NBLOCKS, KLON, KLEV)


    CALL vert_loop_7_2_routine(&
        & 1, KLEV, NCLV, 1, 1, NCLDQS, NCLDQI, NCLDQL, NCLDTOP, NBLOCKS, &
        & PTSPHY, RLMIN, ZEPSEC, RG, PLU, LDCUM, PAPH, &
        & PLUDE)

END PROGRAM
! Base on lines 1096 to 1120 and others
SUBROUTINE vert_loop_7_2_routine(&
    & KLON, KLEV, NCLV, KIDIA, KFDIA, NCLDQS, NCLDQI, NCLDQL, NCLDTOP, NBLOCKS, &
    & PTSPHY, RLMIN, ZEPSEC, RG, PLU_NF, LDCUM_NF, PAPH_NF, &
    & PLUDE_NF)

    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    ! Parameters
    INTEGER(KIND=JPIM) KLEV
    INTEGER(KIND=JPIM) NCLV
    INTEGER(KIND=JPIM) KIDIA 
    INTEGER(KIND=JPIM) KFDIA 
    INTEGER(KIND=JPIM) NCLDQS 
    INTEGER(KIND=JPIM) NCLDQI 
    INTEGER(KIND=JPIM) NCLDQL 
    INTEGER(KIND=JPIM) NCLDTOP
    ! NGPTOT == NPROMA == KLON
    ! INTEGER(KIND=JPIM) NPROMA 
    INTEGER(KIND=JPIM) NBLOCKS 

    ! input
    REAL(KIND=JPRB) PTSPHY
    REAL(KIND=JPRB) RLMIN
    REAL(KIND=JPRB) ZEPSEC
    REAL(KIND=JPRB) RG
    REAL(KIND=JPRB) PLU_NF(NBLOCKS, KLON, KLEV)
    LOGICAL LDCUM_NF(NBLOCKS, KLON)
    REAL(KIND=JPRB) PAPH_NF(NBLOCKS, KLON, KLEV+1)

    ! output
    REAL(KIND=JPRB) PLUDE_NF(NBLOCKS, KLON, KLEV)

    DO JN=1,NBLOCKS,KLON
        CALL inner_loops(&
            & KLON, KLEV, NCLV, KIDIA, KFDIA, NCLDQS, NCLDQI, NCLDQL, NCLDTOP, &
            & PTSPHY, RLMIN, ZEPSEC, RG, PLU_NF(JN,:,:), LDCUM_NF(JN,:), PAPH_NF(JN,:,:), &
            & PLUDE_NF(JN,:,:))

    ENDDO

END SUBROUTINE vert_loop_7_2_routine

SUBROUTINE inner_loops(&
    & KLON, KLEV, NCLV, KIDIA, KFDIA, NCLDQS, NCLDQI, NCLDQL, NCLDTOP, &
    & PTSPHY, RLMIN, ZEPSEC, RG, PLU_NF, LDCUM_NF, PAPH_NF, &
    & PLUDE_NF)

    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    REAL(KIND=JPRB) PTSPHY
    REAL(KIND=JPRB) RLMIN
    REAL(KIND=JPRB) ZEPSEC
    REAL(KIND=JPRB) RG
    REAL(KIND=JPRB) PLU_NF(KLON, KLEV)
    LOGICAL LDCUM_NF(KLON)
    REAL(KIND=JPRB) PAPH_NF(KLON, KLEV+1)

    ! output
    REAL(KIND=JPRB) PLUDE_NF(KLON, KLEV)

    ! temporary scalars
    ! temporary arrays
    REAL(KIND=JPRB) ZDTGDP(KLON)
    REAL(KIND=JPRB) ZDP(KLON)
    REAL(KIND=JPRB) ZGDP(KLON)
    ! Cut away KLEV dimension of ZTP1

    ! Not sure if this causes problems
    ZDTGDP(:) = 0.0
    ZDP(:) = 0.0
    ZGDP(:) = 0.0

    DO JK=NCLDTOP,KLEV
        DO JL=KIDIA,KFDIA   ! LOOP CLASS 3
            ZDP(JL)     = PAPH_NF(JL,JK+1)-PAPH_NF(JL,JK)     ! dp
            ZGDP(JL)    = RG/ZDP(JL)                    ! g/dp
            ZDTGDP(JL)  = PTSPHY*ZGDP(JL)               ! dt g/dp
        ENDDO
        ! To 919

        DO JL=KIDIA,KFDIA
            PLUDE_NF(JL,JK)=PLUDE_NF(JL,JK)*ZDTGDP(JL)
            IF (.NOT.(LDCUM_NF(JL).AND.PLUDE_NF(JL,JK) > RLMIN.AND.PLU_NF(JL,JK+1)> ZEPSEC)) THEN
                PLUDE_NF(JL,JK)=0.0
            ENDIF
        ENDDO
    ENDDO ! on vertical level JK

END SUBROUTINE inner_loops
