PROGRAM vert_loop_mwe

    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM), PARAMETER  :: KLON = 100
    INTEGER(KIND=JPIM), PARAMETER  :: KLEV = 100
    INTEGER(KIND=JPIM), PARAMETER  :: NCLV = 100
    INTEGER(KIND=JPIM), PARAMETER  :: NBLOCKS = 100

    ! Parameters
    INTEGER(KIND=JPIM) KIDIA 
    INTEGER(KIND=JPIM) KFDIA 
    INTEGER(KIND=JPIM) NCLDTOP

    ! input
    REAL(KIND=JPRB) PTSPHY
    REAL(KIND=JPRB) PAPH(NBLOCKS, KLON, KLEV+1)

    ! output
    REAL(KIND=JPRB) PLUDE(NBLOCKS, KLON, KLEV)

    CALL vert_loop_mwe_routine(&
        & KLON, KLEV, NCLV, KIDIA, KFDIA, NCLDTOP, NBLOCKS, &
        & PTSPHY, PAPH, &
        & PLUDE)

END PROGRAM
! Base on lines 1096 to 1120 and others
SUBROUTINE vert_loop_mwe_routine(&
    & KLON, KLEV, NCLV, KIDIA, KFDIA, NCLDTOP, NBLOCKS, &
    & PTSPHY, PAPH_NF, &
    & PLUDE_NF)

    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    ! Parameters
    INTEGER(KIND=JPIM) KLEV
    INTEGER(KIND=JPIM) NCLV
    INTEGER(KIND=JPIM) KIDIA 
    INTEGER(KIND=JPIM) KFDIA 
    INTEGER(KIND=JPIM) NCLDTOP
    ! NGPTOT == NPROMA == KLON
    ! INTEGER(KIND=JPIM) NPROMA 
    INTEGER(KIND=JPIM) NBLOCKS 

    ! input
    REAL(KIND=JPRB) PTSPHY
    REAL(KIND=JPRB) PAPH_NF(NBLOCKS, KLON, KLEV+1)

    ! output
    REAL(KIND=JPRB) PLUDE_NF(NBLOCKS, KLON, KLEV)

    DO JN=1,NBLOCKS,KLON
        CALL inner_loops(&
            & KLON, KLEV, NCLV, KIDIA, KFDIA, NCLDTOP, &
            & PTSPHY, PAPH_NF(JN,:,:), &
            & PLUDE_NF(JN,:,:))

    ENDDO

END SUBROUTINE vert_loop_mwe_routine

SUBROUTINE inner_loops(&
    & KLON, KLEV, NCLV, KIDIA, KFDIA, NCLDTOP, &
    & PTSPHY, PAPH_NF, &
    & PLUDE_NF)

    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    REAL(KIND=JPRB) PTSPHY
    REAL(KIND=JPRB) PAPH_NF(KLON, KLEV+1)

    ! output
    REAL(KIND=JPRB) PLUDE_NF(KLON, KLEV)

    ! temporary arrays
    REAL(KIND=JPRB) ZDTGDP(KLON)

    ! Not sure if this causes problems
    ZDTGDP(:) = 0.0

    DO JK=NCLDTOP,KLEV
        DO JL=KIDIA,KFDIA
            ZDTGDP(JL)  = PTSPHY*PAPH_NF(JL,JK+1)-PAPH_NF(JL,JK)
        ENDDO

        DO JL=KIDIA,KFDIA

            PLUDE_NF(JL,JK)=PLUDE_NF(JL,JK)*ZDTGDP(JL)

        ENDDO
    ENDDO ! on vertical level JK

END SUBROUTINE inner_loops
