PROGRAM map_loop_3
    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM), PARAMETER  :: KLEV = 100
    INTEGER(KIND=JPIM), PARAMETER  :: NBLOCKS = 100

    REAL(KIND=JPRB) INPUT_F(NBLOCKS, KLEV)
    REAL(KIND=JPRB) OUTPUT_F(NBLOCKS, KLEV)

    CALL map_loop_3_routine(KLEV, NBLOCKS, INPUT_F, OUTPUT_F)
    
END PROGRAM

SUBROUTINE map_loop_3_routine(KLEV, NBLOCKS, INPUT_F, OUTPUT_F)
    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM) KLEV
    INTEGER(KIND=JPIM) NBLOCKS

    REAL(KIND=JPRB) INPUT_F(NBLOCKS, KLEV)
    REAL(KIND=JPRB) OUTPUT_F(NBLOCKS, KLEV)
    REAL(KIND=JPRB) TMP_F(NBLOCKS, KLEV)

    TMP_F(:, :) = 0

    DO I=1,NBLOCKS
        DO J=3,KLEV
            TMP_F(I, J) = (INPUT_F(I, J) + INPUT_F(I, J-1) + INPUT_F(I, J-2)) * 3
            OUTPUT_F(I, J) = (TMP_F(I, J) + TMP_F(I, J-2) + TMP_F(I, J-2)) * 3
        ENDDO
    ENDDO

END SUBROUTINE map_loop_3_routine
