PROGRAM mwe_array_order_3
    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM), PARAMETER  :: KLON = 1
    INTEGER(KIND=JPIM), PARAMETER  :: KLEV = 137
    INTEGER(KIND=JPIM), PARAMETER  :: NBLOCKS = 200

    REAL(KIND=JPRB) INP1(KLON, KLEV, NBLOCKS)
    REAL(KIND=JPRB) OUT1(KLON, KLEV, NBLOCKS)

    CALL mwe_array_order_3_routine(&
        & KLON, KLEV, NBLOCKS, &
        & INP1, OUT1)

END PROGRAM

SUBROUTINE mwe_array_order_3_routine(&
        & KLON, KLEV, NBLOCKS,  &
        & INP1, OUT1)

    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM) KLON
    INTEGER(KIND=JPIM) KLEV
    INTEGER(KIND=JPIM) NBLOCKS

    REAL(KIND=JPRB) INP1(KLON, KLEV, NBLOCKS)
    REAL(KIND=JPRB) OUT1(KLON, KLEV, NBLOCKS)
        
    DO JN=1,NBLOCKS
        CALL inner_loops(&
            & KLON, KLEV, &
            & INP1(:, :, JN), OUT1(:, :, JN))
    ENDDO

END SUBROUTINE mwe_array_order_3_routine


SUBROUTINE inner_loops(&
        & KLON, KLEV, &
        & INP1, OUT1)

    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM) KLON
    INTEGER(KIND=JPIM) KLEV
    INTEGER(KIND=JPIM) NCLV
    INTEGER(KIND=JPIM) NCLDQL

    REAL(KIND=JPRB) INP1(KLON, KLEV)
    REAL(KIND=JPRB) OUT1(KLON, KLEV)

    DO JK=1,KLEV
        DO JL=1,KLON
            OUT1(JL, JK) = JK + INP1(JL, JK)
        ENDDO
    ENDDO

END SUBROUTINE inner_loops

