PROGRAM mwe_array_order_2
    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM), PARAMETER  :: KLON = 1
    INTEGER(KIND=JPIM), PARAMETER  :: KLEV = 137
    INTEGER(KIND=JPIM), PARAMETER  :: NCLV = 10
    INTEGER(KIND=JPIM), PARAMETER  :: NBLOCKS = 200
    INTEGER(KIND=JPIM), PARAMETER :: NCLDQL = 4

    REAL(KIND=JPRB) INP1(KLON, KLEV, NBLOCKS)
    REAL(KIND=JPRB) OUT1(KLON, KLEV, NBLOCKS)

    CALL mwe_array_order_2_1_routine(&
        & KLON, KLEV, NBLOCKS, NCLV, NCLDQL, &
        & INP1, OUT1)

END PROGRAM

SUBROUTINE mwe_array_order_2_1_routine(&
        & KLON, KLEV, NBLOCKS, NCLV, NCLDQL, &
        & INP1, OUT1)

    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM) KLON
    INTEGER(KIND=JPIM) KLEV
    INTEGER(KIND=JPIM) NBLOCKS
    INTEGER(KIND=JPIM) NCLV
    INTEGER(KIND=JPIM) NCLDQL

    REAL(KIND=JPRB) INP1(KLON, KLEV, NBLOCKS)
    REAL(KIND=JPRB) OUT1(KLON, KLEV, NBLOCKS)
        
    DO JN=1,NBLOCKS
        DO JK=2,KLEV
            DO JL=1,KLON
                OUT1(JL, JK, JN) = INP1(JL, JK, JN) * 10
                ! OUT1(JL, JK, JN) = JK
            ENDDO
        ENDDO
    ENDDO

END SUBROUTINE mwe_array_order_2_1_routine
