PROGRAM mwe_array_order
    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM), PARAMETER  :: KLON = 1
    INTEGER(KIND=JPIM), PARAMETER  :: KLEV = 137
    INTEGER(KIND=JPIM), PARAMETER  :: NCLV = 10
    INTEGER(KIND=JPIM), PARAMETER  :: NBLOCKS = 200
    INTEGER(KIND=JPIM), PARAMETER :: NCLDQL = 4

    REAL(KIND=JPRB) INP1(KLON, KLEV, NBLOCKS)
    REAL(KIND=JPRB) INP3(KLON, KLEV, NCLV, NBLOCKS)
    REAL(KIND=JPRB) OUT1(KLON, KLEV, NBLOCKS)

    CALL mwe_array_order_routine(&
        & KLON, KLEV, NBLOCKS, NCLV, NCLDQL, &
        & INP1, INP3, OUT1)

END PROGRAM

SUBROUTINE mwe_array_order_routine(&
        & KLON, KLEV, NBLOCKS, NCLV, NCLDQL, &
        & INP1, INP3, OUT1)

    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM) KLON
    INTEGER(KIND=JPIM) KLEV
    INTEGER(KIND=JPIM) NBLOCKS
    INTEGER(KIND=JPIM) NCLV
    INTEGER(KIND=JPIM) NCLDQL

    REAL(KIND=JPRB) INP1(KLON, KLEV, NBLOCKS)
    REAL(KIND=JPRB) INP3(KLON, KLEV, NCLV, NBLOCKS)
    REAL(KIND=JPRB) OUT1(KLON, KLEV, NBLOCKS)
        
    DO JN=1,NBLOCKS
        CALL inner_loops(&
            & KLON, KLEV, NCLV, NCLDQL, &
            & INP1(:, :, JN), INP3(:, :, :, JN), OUT1(:, :, JN))
    ENDDO

END SUBROUTINE mwe_array_order_routine


SUBROUTINE inner_loops(&
        & KLON, KLEV, NCLV, NCLDQL, &
        & INP1, INP3, OUT1)

    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM) KLON
    INTEGER(KIND=JPIM) KLEV
    INTEGER(KIND=JPIM) NCLV
    INTEGER(KIND=JPIM) NCLDQL

    REAL(KIND=JPRB) INP1(KLON, KLEV)
    REAL(KIND=JPRB) INP3(KLON, KLEV, NCLV)
    REAL(KIND=JPRB) OUT1(KLON, KLEV)

    DO JK=1,KLEV
        DO JL=1,KLON
            OUT1(JL, JK) = INP1(JL, JK) + INP3(JL, JK, NCLDQL)
        ENDDO
    ENDDO

END SUBROUTINE inner_loops

