PROGRAM mwe_nested_map
    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM), PARAMETER  :: KLEV = 137
    INTEGER(KIND=JPIM), PARAMETER  :: NCLV = 10
    INTEGER(KIND=JPIM), PARAMETER  :: NBLOCKS = 200
    INTEGER(KIND=JPIM), PARAMETER :: NCLDQI = 3
    INTEGER(KIND=JPIM), PARAMETER :: NCLDQL = 4

    REAL(KIND=JPRB) INP1(NBLOCKS, KLEV)
    REAL(KIND=JPRB) INP2(NBLOCKS, KLEV)
    REAL(KIND=JPRB) INP3(NBLOCKS, KLEV, NCLV)
    REAL(KIND=JPRB) OUT1(NBLOCKS, KLEV)

    CALL mwe_nested_map_routine(&
        & KLEV, NBLOCKS, NCLV, NCLDQI, NCLDQL, &
        & INP1, INP2, INP3, OUT1)

END PROGRAM

SUBROUTINE mwe_nested_map_routine(&
        & KLEV, NBLOCKS, NCLV, NCLDQI, NCLDQL, &
        & INP1, INP2, INP3, OUT1)

    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM) KLEV
    INTEGER(KIND=JPIM) NBLOCKS
    INTEGER(KIND=JPIM) NCLV
    INTEGER(KIND=JPIM) NCLDQI
    INTEGER(KIND=JPIM) NCLDQL

    REAL(KIND=JPRB) INP1(NBLOCKS, KLEV)
    REAL(KIND=JPRB) INP2(NBLOCKS, KLEV)
    REAL(KIND=JPRB) INP3(NBLOCKS, KLEV, NCLV)
    REAL(KIND=JPRB) OUT1(NBLOCKS, KLEV)
    REAL(KIND=JPRB) TMP1(NBLOCKS, KLEV)

    DO JN=1,NBLOCKS
        CALL inner_loops(KLEV, NCLV, NCLDQI, NCLDQL, INP1(JN, :), INP2(JN, :), INP3(JN, :, :), OUT1(JN, :))
    ENDDO

END SUBROUTINE mwe_nested_map_routine

SUBROUTINE inner_loops(&
        & KLEV, NCLV, NCLDQI, NCLDQL, &
        & INP1, INP2, INP3, OUT1)
    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM) KLEV
    INTEGER(KIND=JPIM) NCLV
    INTEGER(KIND=JPIM) NCLDQI
    INTEGER(KIND=JPIM) NCLDQL

    REAL(KIND=JPRB) INP1(KLEV)
    REAL(KIND=JPRB) INP2(KLEV)
    REAL(KIND=JPRB) INP3(KLEV, NCLV)
    REAL(KIND=JPRB) OUT1(KLEV)
    REAL(KIND=JPRB) TMP1(KLEV)

        DO JK=1,KLEV
            DO JM=1,NCLV
                INP3(JK, JM) = JM*1000 + JK
            ENDDO
        ENDDO

        DO JK=1,KLEV
            OUT1(JK) = INP3(JK, NCLDQI) - INP2(JK) + INP1(JK)
        ENDDO
END SUBROUTINE inner_loops
