PROGRAM mwe_arrays_vanish_3
    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM), PARAMETER  :: KLON = 1
    INTEGER(KIND=JPIM), PARAMETER  :: KLEV = 137
    INTEGER(KIND=JPIM), PARAMETER  :: NCLV = 10
    INTEGER(KIND=JPIM), PARAMETER  :: NBLOCKS = 200
    INTEGER(KIND=JPIM), PARAMETER :: NCLDQI = 3
    INTEGER(KIND=JPIM), PARAMETER :: NCLDQL = 4

    REAL(KIND=JPRB) INP1(NBLOCKS, KLON, KLEV)
    REAL(KIND=JPRB) INP3(NBLOCKS, KLON, KLEV, NCLV)
    REAL(KIND=JPRB) OUT1(NBLOCKS, KLON, KLEV)

    CALL mwe_arrays_vanish_3_routine(&
        & KLON, KLEV, NBLOCKS, NCLV, NCLDQI, NCLDQL, &
        & INP1, INP3, OUT1)

END PROGRAM

SUBROUTINE mwe_arrays_vanish_3_routine(&
        & KLON, KLEV, NBLOCKS, NCLV, NCLDQI, NCLDQL, &
        & INP1, INP3, OUT1)

    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM) KLON
    INTEGER(KIND=JPIM) KLEV
    INTEGER(KIND=JPIM) NBLOCKS
    INTEGER(KIND=JPIM) NCLV
    INTEGER(KIND=JPIM) NCLDQI
    INTEGER(KIND=JPIM) NCLDQL

    REAL(KIND=JPRB) INP1(NBLOCKS, KLON, KLEV)
    REAL(KIND=JPRB) INP3(NBLOCKS, KLON, KLEV, NCLV)
    REAL(KIND=JPRB) OUT1(NBLOCKS, KLON, KLEV)
        
    DO JN=1,NBLOCKS
        CALL inner_loops(KLON, KLEV, NCLV, NCLDQI, NCLDQL, INP1(JN, :, :), INP3(JN, :, :, :), OUT1(JN, :, :))
    ENDDO

END SUBROUTINE mwe_arrays_vanish_3_routine

SUBROUTINE inner_loops(&
        & KLON, KLEV, NCLV, NCLDQI, NCLDQL, &
        & INP1, INP3, OUT1)
    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER(KIND=JPIM) KLON
    INTEGER(KIND=JPIM) KLEV
    INTEGER(KIND=JPIM) NCLV
    INTEGER(KIND=JPIM) NCLDQI
    INTEGER(KIND=JPIM) NCLDQL

    REAL(KIND=JPRB) INP1(KLON, KLEV)
    REAL(KIND=JPRB) INP3(KLON, KLEV, NCLV)
    REAL(KIND=JPRB) OUT1(KLON, KLEV)
    REAL(KIND=JPRB) TMP1(KLON, KLEV)
    REAL(KIND=JPRB) TMP2(KLON, KLEV)

    ! TMP1(:, :) = 0
    ! TMP2(:, :) = 0

    DO JK=1,KLEV
        DO JL=1,KLON
            IF (INP3(JL, JK, NCLDQI) > 0.5) THEN
                TMP1(JL, JK) = INP1(JL, JK) + INP3(JL, JK, NCLDQI)
                TMP2(JL, JK) = TMP1(JL, JK) - INP3(JL, JK, NCLDQI)
            ELSE
                TMP1(JL, JK) = 0.0
                TMP2(JL, JK) = 0.0
            ENDIF
        ENDDO
    ENDDO

    DO JK=1,KLEV
        DO JL=1,KLON
            OUT1(JL, JK) = TMP1(JL, JK) + TMP2(JL, JK)
        ENDDO
    ENDDO
END SUBROUTINE inner_loops
