PROGRAM my_roofline_test
    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER, PARAMETER  :: KLON = 10
    INTEGER, PARAMETER  :: KLEV = 10
    INTEGER, PARAMETER  :: KIDIA = 2
    INTEGER, PARAMETER  :: KFDIA = 8

    REAL(KIND=JPRB) :: ARRAY_A(KLON, KLEV)
    REAL(KIND=JPRB) :: ARRAY_B(KLON, KLEV)
    REAL(KIND=JPRB) :: ARRAY_C(KLON, KLEV)

    INTEGER :: JK
    
    CALL my_roofline_test_routine(KLON, KLEV, KIDIA, KFDIA, ARRAY_A, ARRAY_B, ARRAY_C)
END

SUBROUTINE my_roofline_test_routine(KLON, KLEV, KIDIA, KFDIA, ARRAY_A, ARRAY_B, ARRAY_C)
    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER  :: KLON
    INTEGER  :: KLEV
    INTEGER  :: KIDIA
    INTEGER  :: KFDIA
    REAL(KIND=JPRB) :: ARRAY_A(KLON, KLEV)
    REAL(KIND=JPRB) :: ARRAY_B(KLON, KLEV)
    REAL(KIND=JPRB) :: ARRAY_C(KLON, KLEV)
    INTEGER :: JK

    DO JK=1,KLEV
        DO JL=KIDIA,KFDIA
            ARRAY_A(JL,JK) = (ARRAY_B(JL,JK) * ARRAY_C(JL,JK))
        ENDDO
    ENDDO

END SUBROUTINE my_roofline_test_routine

