PROGRAM my_test
    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER, PARAMETER  :: KLON = 10

    REAL(KIND=JPRB) :: ARRAY_A(KLON)
    REAL(KIND=JPRB) :: ARRAY_B(KLON)

    INTEGER :: JK
    
    CALL my_test_routine(KLON, ARRAY_A, ARRAY_B)
END

SUBROUTINE my_test_routine(KLON, ARRAY_A, ARRAY_B)
    INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
    INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13, 300)

    INTEGER  :: KLON
    REAL(KIND=JPRB) :: ARRAY_A(KLON)
    REAL(KIND=JPRB) :: ARRAY_B(KLON)
    INTEGER :: JK

    DO JK=1,KLON
        IF (ARRAY_B(JK) > 1.0) THEN
            ARRAY_A(JK) = JK * 1.0
        ELSE
            ARRAY_A(JK) = 0.0
        ENDIF
    ENDDO

END SUBROUTINE my_test_routine

