"""
Auto-generated FlexClusterArch class
------------------------------------
This file was generated by the generate_arg_cfg function.
"""

class FlexClusterArch:

    def __init__(self):

        # Cluster
        self.num_cluster_x           = 2
        self.num_cluster_y           = 2
        self.num_core_per_cluster    = 3

        self.cluster_tcdm_bank_width = 32
        self.cluster_tcdm_bank_nb    = 128

        self.cluster_tcdm_base       = 0x00000000
        self.cluster_tcdm_size       = 0x100000
        self.cluster_tcdm_remote     = 0x30000000

        self.cluster_heap_base       = 0x00000100
        self.cluster_heap_end        = 0x00100000

        self.cluster_stack_base      = 0x10000000
        self.cluster_stack_size      = 0x00020000

        self.cluster_zomem_base      = 0x18000000
        self.cluster_zomem_size      = 0x00020000

        self.cluster_reg_base        = 0x20000000
        self.cluster_reg_size        = 0x00000200

        # Spatz Vector Unit
        self.spatz_attaced_core_list = []  # Default empty
        self.spatz_num_vlsu_port     = 8
        self.spatz_num_function_unit = 8

        # RedMule
        self.redmule_ce_height       = 64
        self.redmule_ce_width        = 64
        self.redmule_ce_pipe         = 1
        self.redmule_elem_size       = 2
        self.redmule_queue_depth     = 1
        self.redmule_reg_base        = 0x20020000
        self.redmule_reg_size        = 0x00000200

        # IDMA
        self.multi_idma_enable       = 1
        self.idma_outstand_txn       = 16
        self.idma_outstand_burst     = 256

        # HBM
        self.hbm_start_base          = 0xc0000000
        self.hbm_node_addr_space     = 0x4000000
        self.num_node_per_ctrl       = 1
        self.hbm_chan_placement      = [2, 2, 2, 2]

        # NoC
        self.noc_outstanding         = 64
        self.noc_link_width          = 4096

        # System
        self.instruction_mem_base    = 0x80000000
        self.instruction_mem_size    = 0x00010000

        self.soc_register_base       = 0x90000000
        self.soc_register_size       = 0x00010000
        self.soc_register_eoc        = 0x90000000
        self.soc_register_wakeup     = 0x90000004

        # Synchronization
        self.sync_base               = 0x40000000
        self.sync_interleave         = 0x00000080
        self.sync_special_mem        = 0x00000040
