name: Code Quality

on:
  push:
    branches: [ main, ci-fix ]
  pull_request:
    branches: [ main, ci-fix ]

env:
  UV_FROZEN: 1 # sync without updating uv.lock
  UV_NO_DEV: 1 # don't install dev dependency group by default
  UV_NO_EDITABLE: 1 # don't install dace in editable mode

jobs:
  linting:
    if: "!contains(github.event.pull_request.labels.*.name, 'no-ci')"
    name: pre-commit
    runs-on: ubuntu-latest

    steps:
    - name: Check repository
      uses: actions/checkout@v7

    - name: Set up uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: '3.10'
        enable-cache: true
        pyproject-file: pyproject.toml
        cache-dependency-glob: pyproject.toml

    # In one place we should check that `pyproject.toml` and `uv.lock` are up-to-date.
    # This place is as good any other. We un-freeze to lock file to do so.
    - name: Check that uv.lock is up-to-date
      run: UV_FROZEN=0 uv lock --check

    - name: Run linting tools
      id: lint
      run: uv run --only-group=linting pre-commit run --show-diff-on-failure --color=always --all-files
