name: NASA/NOAA Pace repository build test

on:
    workflow_dispatch:

defaults:
    run:
        shell: bash

jobs:
    build_pace:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.8.10]

        steps:
        - uses: actions/checkout@v2
          with:
                repository: 'git@github.com:GEOS-ESM/pace.git'
                ref: 911368
                submodules: 'recursive'
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
                python-version: ${{ matrix.python-version }}
        - name: Install dependencies & pull correct DaCe
          run: |
            cd pace
            python -m pip install --upgrade pip
            pip install -e external/gt4py
            pip install -e external/dace
            pip install -r requirements_dev.txt
            cd external/dace
            git checkout ${{ github.sha }}
            cd ../..
        - name: Download data
          run: |
            cd pace
            mkdir -p test_data
            cd test_data
            wget https://portal.nccs.nasa.gov/datashare/astg/smt/pace-regression-data/8.1.3_c12_6_ranks_standard.Remapping.tar.gz
            tar -xzvf 8.1.3_c12_6_ranks_standard.Remapping.tar.gz
            cd ../..
        - name: Run regression test of Remapping
          run: |
            export FV3_DACEMODE=BuildAndRun
            export PACE_CONSTANTS=GFS
            cd pace
            pytest -v -s --data_path=./test_data/8.1.3/c12_6ranks_standard/dycore \
                --backend=dace:cpu --which_modules=Remapping --which_rank=0 \
                --threshold_overrides_file=./fv3core/tests/savepoint/translate/overrides/standard.yaml \
                ./fv3core/tests/savepoint
