name: NASA/NOAA Pace repository build test

on:
  workflow_dispatch:

defaults:
    run:
      shell: bash

jobs:
    build_pace:
      runs-on: ubuntu-latest
      strategy:
          matrix:
              python-version: [3.8.12]

      steps:
      - uses: actions/checkout@v2
        with:
              repository: 'GEOS-ESM/pace'
              ref: 'ci/DaCe'
              submodules: 'recursive'
              path: 'pace'
      - uses: actions/checkout@v2
        with: 
            path: 'dace'
            submodules: 'recursive'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
              python-version: ${{ matrix.python-version }}
      - name: Install library dependencies
        run: |
          sudo apt-get install libopenmpi-dev libboost-all-dev
      # Because Github doesn't allow us to do a git checkout in code
      # we use a trick to checkout DaCe first (not using the external submodule)    
      # install the full suite via requirements_dev, then re-install the correct DaCe
      - name: Install Python packages 
        run: |
          python -m pip install --upgrade pip wheel setuptools
          cd pace
          pip install -r requirements_dev.txt
          pip install -e ../dace
      - name: Download data
        run: |
          cd pace
          mkdir -p test_data
          cd test_data
          wget https://portal.nccs.nasa.gov/datashare/astg/smt/pace-regression-data/8.1.3_c12_6_ranks_standard.D_SW.tar.gz
          tar -xzvf 8.1.3_c12_6_ranks_standard.D_SW.tar.gz
          wget https://portal.nccs.nasa.gov/datashare/astg/smt/pace-regression-data/8.1.3_c12_6_ranks_standard.RiemSolverC.tar.gz
          tar -xzvf 8.1.3_c12_6_ranks_standard.RiemSolverC.tar.gz
          wget https://portal.nccs.nasa.gov/datashare/astg/smt/pace-regression-data/8.1.3_c12_6_ranks_standard.Remapping.tar.gz
          tar -xzvf 8.1.3_c12_6_ranks_standard.Remapping.tar.gz
          cd ../..
      - name: "Regression test: Riemman Solver on C-grid"
        run: |
          export FV3_DACEMODE=BuildAndRun
          export PACE_CONSTANTS=GFS
          cd pace
          pytest -v -s --data_path=./test_data/8.1.3/c12_6ranks_standard/dycore \
              --backend=dace:cpu --which_modules=Riem_Solver_C \
              --threshold_overrides_file=./fv3core/tests/savepoint/translate/overrides/standard.yaml \
              ./fv3core/tests/savepoint
      - name: "Regression test: D-grid shallow water lagrangian dynamics (D_SW)"
        run: |
          export FV3_DACEMODE=BuildAndRun
          export PACE_CONSTANTS=GFS
          cd pace
          pytest -v -s --data_path=./test_data/8.1.3/c12_6ranks_standard/dycore \
              --backend=dace:cpu --which_modules=D_SW \
              --threshold_overrides_file=./fv3core/tests/savepoint/translate/overrides/standard.yaml \
              ./fv3core/tests/savepoint
      - name: "Regression test: Remapping (on rank 0 only)"
        run: |
          export FV3_DACEMODE=BuildAndRun
          export PACE_CONSTANTS=GFS
          cd pace
          pytest -v -s --data_path=./test_data/8.1.3/c12_6ranks_standard/dycore \
              --backend=dace:cpu --which_modules=Remapping --which_rank=0 \
              --threshold_overrides_file=./fv3core/tests/savepoint/translate/overrides/standard.yaml \
              ./fv3core/tests/savepoint
