name: DaCe Verilator Compatibility Check
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for the trigger'
        required: true
        default: 'Check compatibility'
  schedule:
    - cron: '0 0 1 * *' # monthly
jobs:
  build:
    strategy:
      matrix:
        verilator_version: ['4.028', '4.034', '4.036', '4.100', 'master']
    runs-on: ubuntu-20.04
    steps:
      - name: trigger reason
        run: echo "Trigger Reason:" ${{ github.event.inputs.reason }}
      - uses: actions/checkout@v2
      - name: checkout submodules
        run: git submodule update --init --recursive
      - name: install apt packages
        run: sudo apt-get update && sudo apt-get -y install git make autoconf g++ flex bison libfl2 libfl-dev
      - name: compile verilator
        run: git clone https://github.com/verilator/verilator.git && cd verilator && git fetch origin && if [ ! "${{ matrix.verilator_version }}" == "master" ]; then  git checkout v${{ matrix.verilator_version }}; fi && autoconf && ./configure && make -j2 && sudo make install
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - uses: BSFishy/pip-action@v1
        with:
          packages: pytest
          requirements: requirements.txt
      - name: install dace
        run: python3 -m pip install .
      - run: pytest -m "verilator"
