# Copyright 2019-2026 ETH Zurich and the DaCe authors. All rights reserved.
"""
Tests for ``dace.sdfg.construction_utils.get_parent_map_and_loop_scopes``.

Uses the DaCe Python frontend (``@dace.program``, ``dace.map``, ``range``)
to build a realistic HPC-style SDFG that mixes maps, loops, nested SDFGs,
scalar-dependent dynamic ranges, and 3D tensor accesses::

    @dace.program kernel(A, offsets):
        for i in dace.map[0:N]:                 # Map "kernel_*"
            inner_compute(A, offsets[i, :], i)

    @dace.program inner_compute(A, off_row, ii):
        for j in range(M):                      # LoopRegion "for_*" (j)
            s = off_row[j]                       # scalar read
            for idx in range(10):                # LoopRegion "for_*" (idx)
                for k in dace.map[0:K]:          # Map "inner_compute_*"
                    A[k, ii, j+s+idx] += 1.0     # Tasklet
"""
import dace
from dace.sdfg.state import LoopRegion
from dace.transformation.helpers import get_parent_map_and_loop_scopes

N, M, K = 4, 4, 5
COLS = M + 10  # enough room for j + offset + 9


@dace.program
def inner_compute(A: dace.float64[K, N, COLS], off_row: dace.int64[M], ii: dace.int64):
    for j in range(M):
        s = off_row[j]
        for idx in range(10):
            for k in dace.map[0:K]:
                A[k, ii, j + s + idx] = A[k, ii, j + s + idx] + 1.0


@dace.program
def kernel(A: dace.float64[K, N, COLS], offsets: dace.int64[N, M]):
    for i in dace.map[0:N]:
        inner_compute(A, offsets[i, :], i)


def _get_sdfg():
    """Parse the frontend programs into an unsimplified SDFG."""
    return kernel.to_sdfg(simplify=False)


def _find_inner_map(sdfg):
    """Find the innermost map (the k-map inside inner_compute)."""
    for n, st in sdfg.all_nodes_recursive():
        if isinstance(n, dace.sdfg.nodes.MapEntry):
            # The inner map is generated by dace.map[0:K] inside
            # inner_compute -- its label contains "inner_compute"
            if "inner_compute" in n.label:
                return n, st
    raise RuntimeError("Could not find inner_compute map")


def _find_outer_map(sdfg):
    """Find the outer map (the i-map in kernel)."""
    for n, st in sdfg.all_nodes_recursive():
        if isinstance(n, dace.sdfg.nodes.MapEntry):
            if "kernel" in n.label:
                return n, st
    raise RuntimeError("Could not find kernel map")


def _find_inner_tasklet(sdfg):
    """Find the tasklet that performs the A[...] += 1.0 increment."""
    for n, st in sdfg.all_nodes_recursive():
        if isinstance(n, dace.sdfg.nodes.Tasklet):
            code = n.code.as_string if hasattr(n.code, 'as_string') else str(n.code)
            if "+ 1.0" in code or "+1.0" in code or "+ 1" in code:
                return n, st
    raise RuntimeError("Could not find increment tasklet")


def test_inner_map_sees_two_loops_and_outer_map():
    """
    The k-map inside inner_compute sits inside:
      LoopRegion(idx) -> LoopRegion(j) -> NestedSDFG -> Map(i)

    get_parent_map_and_loop_scopes should return 3 scopes:
      2 LoopRegions + 1 MapEntry.
    """
    sdfg = _get_sdfg()
    me, st = _find_inner_map(sdfg)
    parents = get_parent_map_and_loop_scopes(sdfg, me, st)

    loops = [p for p in parents if isinstance(p, LoopRegion)]
    maps = [p for p in parents if isinstance(p, dace.sdfg.nodes.MapEntry)]

    assert len(loops) == 2, (f"Expected 2 LoopRegions, got {len(loops)}: "
                             f"{[p.label for p in loops]}")
    assert len(maps) == 1, (f"Expected 1 MapEntry (outer i-map), got {len(maps)}: "
                            f"{[p.label for p in maps]}")


def test_inner_tasklet_sees_inner_map_plus_all_scopes():
    """
    The increment tasklet is inside the k-map, so it should see
    one extra MapEntry compared to the k-map itself:
      MapEntry(k-map) + LoopRegion(idx) + LoopRegion(j) + MapEntry(i-map)
    = 2 maps + 2 loops = 4 parent scopes.
    """
    sdfg = _get_sdfg()
    t, st = _find_inner_tasklet(sdfg)
    parents = get_parent_map_and_loop_scopes(sdfg, t, st)

    loops = [p for p in parents if isinstance(p, LoopRegion)]
    maps = [p for p in parents if isinstance(p, dace.sdfg.nodes.MapEntry)]

    assert len(loops) == 2
    assert len(maps) == 2
    assert len(parents) == 4


def test_outer_map_has_no_parent_scopes():
    """The outermost i-map in kernel has no parent scopes."""
    sdfg = _get_sdfg()
    me, st = _find_outer_map(sdfg)
    parents = get_parent_map_and_loop_scopes(sdfg, me, st)
    assert len(parents) == 0


if __name__ == "__main__":
    test_inner_map_sees_two_loops_and_outer_map()
    test_inner_tasklet_sees_inner_map_plus_all_scopes()
    test_outer_map_has_no_parent_scopes()
